"""One-shot, guarded integration from inspected commits. Removed after CI passes."""
from pathlib import Path
import subprocess,re
root=Path.cwd(); base=root/'DTH-3D-Commerce'
old_ref='ace6563ee424759ed6d56879a37a14c8c095c4c2'
def old(name):
    return subprocess.check_output(['git','show',old_ref+':DTH-3D-Commerce/'+name]).decode()
def edit(name, fn):
    p=base/name;p.write_text(fn(p.read_text()))
def replace(s,a,b):
    assert s.count(a)==1, ('anchor changed',a,s.count(a))
    return s.replace(a,b,1)
assert subprocess.check_output(['git','merge-base','HEAD','f4d6ed0cfc00b52f2667099ff1a3a7f101f028ed']).decode().strip()=='f4d6ed0cfc00b52f2667099ff1a3a7f101f028ed'
for name in ['frontend/src/shop/account/AccountPage.jsx','frontend/src/shop/account/AccountPage.module.css','shared/account.mjs','tests/account.test.mjs','tests/account.integration.test.mjs','tests/browser/account.py','frontend/src/shop/useStore.jsx']:
    p=base/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(old(name))
p=base/'backend/commerce/app.mjs';s=p.read_text()
s=replace(s,"import express from 'express';","import express from 'express';\nimport { vehiclePreference, orderQuery, literalSearch } from '../../shared/account.mjs';")
s=replace(s,'role: user.role });',"role: user.role, savedVehicleId: user.savedVehicleId || '', createdAt: user.createdAt });")
prior=old('backend/commerce/app.mjs');start=prior.index('  // Account routes');end=prior.index("  router.get('/orders',",start)
s=replace(s,"  router.get('/orders',",prior[start:end]+"  router.get('/orders',")
p.write_text(s)
edit('backend/commerce/models.mjs',lambda s: replace(replace(s,"const User = mongoose.model('StoreUser', new Schema({","const User = mongoose.model('StoreUser', new Schema({\n  savedVehicleId: { type: String, default: '' },"),"orderSchema.index({ userId: 1, idempotencyKey: 1 }, { unique: true });","orderSchema.index({ userId: 1, idempotencyKey: 1 }, { unique: true });\norderSchema.index({ userId: 1, createdAt: -1, _id: -1 });"))
p=base/'frontend/src/shop/api.js';s=p.read_text();s=re.sub(r'// export async function createOrder[\s\S]*?\n// }\n','',s,count=1)
s=replace(s,"  const result = await request(`/auth/${mode}`, { method: 'POST', body: JSON.stringify(credentials) });\n  return result.user;","  if (!['login', 'register'].includes(mode)) throw new Error('Unknown authentication action.');\n  const result = await request(`/auth/${mode}`, { method: 'POST', body: JSON.stringify(credentials) });\n  if (!result.user?.id || typeof result.user.email !== 'string') throw new Error('The account response could not be verified. Refresh and try again.');\n  return result.user;")
s=replace(s,"  if (!PREVIEW) await request('/auth/logout', { method: 'POST', body: '{}' });","  if (!PREVIEW) {\n    try { await request('/auth/logout', { method: 'POST', body: '{}' }); }\n    catch (error) { if (error.status !== 401) throw error; }\n  }")
s+='\nexport async function saveAccountVehicle'+old('frontend/src/shop/api.js').split('export async function saveAccountVehicle',1)[1];p.write_text(s)
p=base/'frontend/src/shop/StoreApp.jsx';s="import AccountPage from './account/AccountPage';\n"+p.read_text();s=replace(s,'<Route path="account" element={<Account />} />','<Route path="account" element={<AccountPage />} />')
start=s.index('function Account() {');end=s.index('function Admin()',start);s=s[:start]+s[end:]
s=replace(s,'PREVIEW, authenticate, createOrder, deleteAccount, loadOrders,','PREVIEW, createOrder,');p.write_text(s)
edit('shared/account.mjs',lambda s: replace(s,"  const rawPage = typeof query.page === 'string' ? query.page : '1';","  if (query.page !== undefined && typeof query.page !== 'string') throw new InputError('Invalid order page.');\n  const rawPage = query.page ?? '1';"))
p=base/'frontend/src/shop/useStore.jsx';s=p.read_text();s=replace(s,"setVehicle(next?.savedVehicleId || '');","setVehicle(current => next?.savedVehicleId || (next && !previous ? current : ''));")
s=replace(s,'    if (!data.vehicles.some',"    if (!Number.isSafeInteger(quantity) || quantity < 1 || quantity > 10 || product.active === false) {\n      setNotice('Choose a quantity from 1 to 10.'); return false;\n    }\n    if (!data.vehicles.some")
s=replace(s,'  const [notice, setNotice]',"  const [authError, setAuthError] = useState('');\n  const [authRetry, setAuthRetry] = useState(0);\n  const retrySession = useCallback(() => setAuthRetry(value => value + 1), []);\n  const [notice, setNotice]")
s=replace(s,'    setAuthLoading(false);',"    setAuthLoading(false);\n    setAuthError('');")
s=replace(s,'    const epoch = authEpoch.current;',"    const epoch = authEpoch.current;\n    setAuthLoading(true); setAuthError('');")
s=replace(s,'    }).catch(() => {}).finally(() => { if (live) setAuthLoading(false); });',"    }).catch(e => { if (live && epoch === authEpoch.current) setAuthError(e.message); }).finally(() => { if (live) setAuthLoading(false); });")
s=replace(s,'  }, [setUser]);','  }, [setUser, authRetry]);')
s=replace(s,'setUser, authLoading, add,','setUser, authLoading, authError, retrySession, add,');s=replace(s,'user, authLoading, notice, lastOrder]','user, authLoading, authError, notice, lastOrder]');p.write_text(s)
p=base/'frontend/src/shop/account/AccountPage.jsx';s=p.read_text()
s=replace(s,"import s from './AccountPage.module.css';","import s from './AccountPage.module.css';\nimport AccountVisual from './AccountVisual';\nimport ProductImage from '../catalog/components/ProductImage';")
s=replace(s,'  const store = useStore(), live = useLive(), lock = useRef(false);','  const store = useStore(), live = useLive(), lock = useRef(false), fieldId = useId();')
for label,attr in [('Make','make'),('Model','model'),('Year','year')]:
    s=replace(s,f'<label className={{s.field}}>{label}<select',f'<div className={{s.field}}><label htmlFor={{`${{fieldId}}-{attr}`}}>{label}</label><select id={{`${{fieldId}}-{attr}`}}')
    pos=s.index('Choose '+attr,s.index('function VehicleForm'));close=s.index('</select></label>',pos);s=s[:close]+s[close:].replace('</select></label>','</select></div>',1)
s=replace(s,'<div className={s.orbitArt} aria-hidden="true"><span /><span /><span /><b>YOUR<br />NEXT<br /><em>BUILD.</em></b></div>','<AccountVisual />')
s=replace(s,'<div className={s.brandFoot}><span>01 / YOUR SPACE</span><Icon name="arrow" /></div>','<div className={s.brandFoot}><span>Built around you.</span><Icon name="arrow" /></div>')
s=replace(s,"  useEffect(() => { document.title = 'Account — DTH Parts Studio'; }, []);","  useEffect(() => { const previous = document.title; document.title = 'Account — DTH Parts Studio'; return () => { document.title = previous; }; }, []);")
s=replace(s,'if (live) setResult(order);','if (live) setResult({ id, order });');s=replace(s,'result ? <OrderContent order={result} />','result?.id === id ? <OrderContent order={result.order} />')
s=replace(s,'<p className={s.fine}>Compatibility uses the demonstration dataset.</p>','')
s=replace(s,'      const vehicle = store.data.vehicles.find(v => v.id === line.vehicleId);','      const vehicle = store.data.vehicles.find(v => v.id === line.vehicleId);\n      const product = store.data.products.find(p => p.id === line.productId);')
s=replace(s,'return <li key={`${line.productId}:${line.vehicleId}`}><div><strong>','return <li key={`${line.productId}:${line.vehicleId}`}>{product && <Link className={s.receiptThumb} to={`/products/${product.slug}`} aria-label={`View ${line.name}`}><ProductImage product={product} /></Link>}<div className={s.receiptInfo}><strong>')
s=replace(s,'const lock = useRef(false), live = useLive(), errorBox = useRef(null);','const lock = useRef(false), live = useLive(), errorBox = useRef(null), title = useRef(null);')
s=replace(s,"  const registering = mode === 'register';","  const registering = mode === 'register';\n  useEffect(() => { title.current?.focus({ preventScroll: true }); }, [mode]);")
s=replace(s,"<h1>{registering ? 'Create account.' : 'Welcome back.'}</h1>","<h1 ref={title} tabIndex={-1}>{registering ? 'Create account.' : 'Welcome back.'}</h1>")
s=replace(s,' : PREVIEW ? <div',' : store.authError ? <div className={s.preview}><h1>Session unavailable.</h1><Notice error>{store.authError}</Notice><button className={s.primary} onClick={store.retrySession}>Try again</button></div> : PREVIEW ? <div');p.write_text(s)
edit('frontend/src/shop/account/AccountPage.module.css',lambda s:s+(root/'.github/account-motion.css').read_text())
edit('.gitignore',lambda s:s+'\n# Local verification evidence\ntest-results/\n')
edit('tests/account.test.mjs',lambda s:s+"\ntest('Reject non-string order page', () => { assert.throws(() => orderQuery({page: {$gt: 0}})); assert.throws(() => orderQuery({page: ['1']})); });\n")
edit('tests/account.integration.test.mjs',lambda s:replace(s,'demoAcknowledged: true };','demoAcknowledged: true, expectedTotal: p.price * 2 };'))
p=base/'tests/browser/account.py';s=p.read_text().replace('import json, re, uuid','import json, re, uuid, os')
s=s.replace('p.chromium.launch(headless=True, args=','p.chromium.launch(headless=True, executable_path=os.environ.get(\'CHROMIUM_EXECUTABLE\') or None, args=')
s=s.replace("    page.on('pageerror'","    page.set_default_timeout(15000)\n    page.on('pageerror'")
s=s.replace("        page.get_by_role('checkbox').check()","        page.get_by_role('button', name='Review order', exact=True).click()\n        page.get_by_role('checkbox').check()")
s=s.replace("        checked('Login page renders","        expect(page.locator('[data-account-scene=ready]')).to_be_visible()\n        page.get_by_role('button', name='Pause studio animation').click()\n        expect(page.locator('[data-account-scene]')).to_have_attribute('data-motion', 'off')\n        screenshot(page, '01-studio-3d-paused')\n        page.get_by_role('button', name='Play studio animation').click()\n        checked('Real 3D renders; pause and play work')\n        checked('Login page renders")
s=s.replace("        page.goto(base + '/products/apex-suspension')","        page.goto(base + '/shop')\n        expect(page.get_by_role('heading', name='Apex Coilover', exact=True)).to_be_visible()\n        page.get_by_role('heading', name='Apex Coilover', exact=True).get_by_role('link').click()\n        page.get_by_role('link', name='Open product & 3D').click()\n        page.wait_for_url('**/products/apex-suspension')")
s=s.replace("        checked('Logout revokes server session')","        checked('Logout revokes server session')\n        page.get_by_label('Email', exact=True).fill(email)\n        page.get_by_label('Password', exact=True).fill('wrong password sample')\n        page.get_by_role('button', name='Sign in', exact=True).click()\n        expect(page.get_by_role('alert')).to_contain_text('incorrect')\n        checked('Wrong password is rejected without signing in')")
s=s.replace("        assert not errors, errors","        page.goto(base + '/account')\n        page.get_by_role('button', name='Sign out', exact=True).click()\n        for width in [320, 390, 768, 1440]:\n            page.set_viewport_size({'width': width, 'height': 900})\n            page.goto(base + '/account')\n            expect(page.get_by_role('heading', name='Welcome back.')).to_be_visible()\n            no_overflow(page)\n            screenshot(page, 'sign-in-' + str(width))\n        expect(page.locator('[data-account-scene]')).to_have_attribute('data-motion', 'off')\n        checked('Login mobile layouts and 3D reduced motion verified')\n        assert not errors, errors")
p.write_text(s)
quality=subprocess.check_output(['git','show',old_ref+':.github/workflows/account-quality.yml']).decode().replace('branches: [feat/account-studio]','branches: [feat/account-commerce]').replace('Account Studio quality','Account Commerce quality').replace('account-studio-evidence','account-commerce-evidence')
(root/'.github/workflows/account-quality.yml').write_text(quality)
# Protect exactly the user's existing model/shop/checkout files from accidental downgrade.
assert 'expectedTotal !== quote.total' in (base/'backend/commerce/app.mjs').read_text()
assert 'displayedTotal' in (base/'frontend/src/shop/api.js').read_text()
assert 'function ProductDetails' in (base/'frontend/src/shop/StoreApp.jsx').read_text()
print('Integrated Account into feature/3d-store; current checkout preserved.')
