import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {count,metrics,coverage,sortRows,relativeTime,readQuery,appendReply,REPLIES,connectionLabel,vehicleName} from '../frontend/src/shop/admin/ops18b/opsPro.logic.mjs';
import {torus,rotation,multiply} from '../frontend/src/shop/admin/ops18b/mechanism.webgl.mjs';
for(const bad of [null,undefined,NaN,Infinity,-1,.5,'10',{}])test(`reject invalid count ${String(bad)}`,()=>assert.equal(count(bad),null));
test('zero and integer metrics are valid',()=>{assert.equal(count(0),0);assert.equal(count(10),10);});
test('queue metrics describe supplied page only',()=>assert.deepEqual(metrics([{status:'open',unread:3},{status:'resolved',unread:0},{status:'open',unread:2}]),{loaded:3,open:2,unread:2,messages:5}));
test('missing rows safely produce an empty page',()=>assert.deepEqual(metrics(null),{loaded:0,open:0,unread:0,messages:0}));
test('catalog ratio comes from real counts',()=>assert.deepEqual(coverage({products:20,active:15}),{total:20,active:15,hidden:5,percent:75}));
test('empty catalog has a zero ratio',()=>assert.equal(coverage({products:0,active:0}).percent,0));
test('missing and inconsistent counts are never fabricated',()=>{assert.equal(coverage(null).percent,null);assert.equal(coverage({products:1,active:2}).percent,null);});
test('unread sorting preserves input and does not invent priority',()=>{const items=[{id:'a',unread:0,updatedAt:'2026-01-02'},{id:'b',unread:2,updatedAt:'2026-01-01'}];assert.equal(sortRows(items,'unread')[0].id,'b');assert.equal(items[0].id,'a');assert.equal(sortRows(items,'recent')[0].id,'a');});
test('relative time missing and future safe',()=>{assert.equal(relativeTime('bad'),'—');assert.equal(relativeTime('2026-01-01',0),'Just now');assert.equal(relativeTime('2026-01-01',Date.parse('2026-01-01T01:00:00Z')),'1h ago');});
test('query defaults and constraints',()=>{assert.equal(readQuery('page=-2&status=hidden&q=a').page,1);assert.equal(readQuery('status=hidden').status,'');assert.equal(readQuery('page=2').page,2);assert.equal(readQuery('thread=../../secret').invalidThread,true);assert.equal(readQuery('thread=../../secret').id,'');});
test('query keeps valid UUID and clamps search',()=>{const q=readQuery('thread=11111111-1111-4111-8111-111111111111&q='+ 'x'.repeat(200));assert.ok(q.id);assert.equal(q.q.length,100);});
test('reply insertion preserves existing draft',()=>assert.equal(appendReply('Hello','Details'),'Hello\n\nDetails'));
test('reply insertion never truncates silently',()=>assert.equal(appendReply('x'.repeat(3000),'Details'),null));
test('empty draft accepts a template',()=>assert.equal(appendReply('','  Hello  '),'Hello'));
test('bad template input is rejected',()=>{assert.equal(appendReply(null,'hello'),null);assert.equal(appendReply('',''),null);});
test('templates contain no invented quotes or fitment verdicts',()=>{assert.equal(REPLIES.length,3);REPLIES.forEach(r=>{assert.ok(r.text.length<3000);assert.ok(r.id);assert.doesNotMatch(r.text,/\b100%\b|\bVND\b/);});});
test('status is a support connection, not customer presence',()=>{assert.equal(connectionLabel('live'),'Support connected');assert.equal(connectionLabel('offline'),'Support offline');});
test('vehicle captions never require a year',()=>{assert.equal(vehicleName({make:'Yamaha',model:'NVX V2'}),'Yamaha NVX V2');assert.equal(vehicleName(null),'No saved vehicle');});
test('procedural torus has valid indices and unit normals',()=>{const m=torus(1,.1,24,8);assert.ok(m.indices.every(i=>i>=0&&i<m.pos.length/3));assert.ok(m.pos.every(Number.isFinite));for(let i=0;i<m.normal.length;i+=3)assert.ok(Math.abs(Math.hypot(...m.normal.slice(i,i+3))-1)<1e-5);});
test('camera rotations are finite and deterministic',()=>{const r=rotation(.2,.3,.4);assert.ok([...r].every(Number.isFinite));assert.equal(r[15],1);assert.deepEqual(multiply(rotation(0,0,0),r),r);});
const root=new URL('../frontend/src/shop/admin/ops18b/',import.meta.url);
test('3D has bounded DPR and disposal',async()=>{const code=await readFile(new URL('mechanism.webgl.mjs',root),'utf8');assert.match(code,/devicePixelRatio\|\|1,1\.5/);assert.match(code,/deleteBuffer/);assert.match(code,/deleteProgram/);assert.match(code,/cancelAnimationFrame/);assert.doesNotMatch(code,/setInterval|fetch\(/);});
test('scene waits for intro and pauses for typing/visibility',async()=>{const code=await readFile(new URL('Mechanism.jsx',root),'utf8');assert.match(code,/data-dth-intro-state/);assert.match(code,/!typing/);assert.match(code,/!covered/);assert.match(code,/compact\|\|reduced\|\|saveData/);});
test('optional composer slot cannot send messages',async()=>{const c=await readFile(new URL('../frontend/src/shop/support/ChatThread.jsx',import.meta.url),'utf8');assert.match(c,/composerTools=null/);assert.match(c,/value\.length<=3000/);assert.match(c,/!sending&&!pending/);assert.match(c,/const base=`\/chat\/conversations/);assert.match(c,/clientId:draft.clientId/);});
test('admin access guards are still present',async()=>{const code=await readFile(new URL('../frontend/src/shop/admin/AdminLayout.jsx',import.meta.url),'utf8');assert.match(code,/store\.user\?\.role!=='admin'/);assert.match(code,/MODE!=='api'/);assert.match(code,/ops18b\/OverviewPro/);});
test('new UI does not write product or order data',async()=>{for(const name of ['OverviewPro.jsx','InboxPro.jsx']){const code=await readFile(new URL(name,root),'utf8');assert.doesNotMatch(code,/method:'DELETE'|method:'PATCH'/);assert.doesNotMatch(code,/dangerouslySetInnerHTML/);}});
