import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { normalizeBag, addBagLine, changeBagQuantity, removeBagLine, describeBag, lineKey, validCartPrice } from '../frontend/src/shop/cart/cart.logic.mjs';
import { createCartState } from '../frontend/src/shop/cart/cartState.mjs';
const a={id:'apex-suspension',slug:'apex-suspension',name:'Apex Coilover',category:'suspension',price:2800000,active:true,vehicleIds:['street-155','touring-400']};
const b={id:'vector-suspension',slug:'vector-suspension',name:'Vector Coilover',category:'suspension',price:2200000,active:true,vehicleIds:['road-300']};
const data={products:[a,b],vehicles:[{id:'street-155',make:'Demo Moto',model:'Street 155',year:2022},{id:'road-300',make:'Demo Moto',model:'Road 300',year:2024},{id:'touring-400',make:'Demo Moto',model:'Touring 400',year:2024}]};
const item=(quantity=1,vehicleId='street-155',productId=a.id)=>({productId,vehicleId,quantity});
const clone=x=>JSON.parse(JSON.stringify(x));
const freeze=x=>{Object.values(x).forEach(v=>{if(v&&typeof v==='object')freeze(v);});return Object.freeze(x);};
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');

for(const invalid of [null,undefined,{},'x',123]) test(`invalid stored bag ${String(invalid)} is empty`,()=>assert.deepEqual(normalizeBag(invalid),[]));
for(const quantity of [-1,0,11,1.5,NaN,Infinity,'2',null]) test(`reject quantity ${String(quantity)}`,()=>assert.equal(addBagLine([],a.id,'street-155',quantity,data).ok,false));
for(const price of [-1,0,1.5,NaN,Infinity,1000000001,'100',null,undefined]) test(`reject catalog price ${String(price)}`,()=>assert.equal(validCartPrice(price),false));
test('storage retains only the three established cart fields',()=>assert.deepEqual(normalizeBag([{...item(),price:1,role:'admin'}]),[item()]));
test('normalization merges duplicate product/vehicle keys without exceeding ten',()=>assert.deepEqual(normalizeBag([item(7),item(6)]),[item(10)]));
test('normalization keeps two vehicles separate',()=>assert.equal(normalizeBag([item(),item(2,'touring-400')]).length,2));
test('invalid storage rows are not treated as valid items',()=>assert.deepEqual(normalizeBag([item(),{...item(),vehicleId:'../bad'},null,{...item(),quantity:'3'}]),[item()]));
test('storage is bounded to twenty unique lines',()=>assert.equal(normalizeBag(Array.from({length:30},(_,i)=>item(1,'street-155',`p-${i}`))).length,20));
test('add does not mutate incoming bag or catalog',()=>{const bag=freeze([item()]),d=freeze(clone(data)); const r=addBagLine(bag,a.id,'street-155',2,d); assert.equal(r.ok,true);assert.equal(r.bag[0].quantity,3);assert.equal(bag[0].quantity,1);});
test('add rereads current catalog, never accepts stale product metadata',()=>{const r=addBagLine([],a.id,'street-155',1,{...data,products:[{...a,active:false}]});assert.equal(r.ok,false);});
test('unknown product is rejected',()=>assert.equal(addBagLine([],'missing','street-155',1,data).ok,false));
test('unknown vehicle is not incompatible or acceptable',()=>{const r=addBagLine([],a.id,'unknown',1,data);assert.equal(r.ok,false); assert.equal(describeBag([item(1,'unknown')],data).lines[0].match,'unknown');});
test('known mismatching vehicle is rejected',()=>assert.equal(addBagLine([],a.id,'road-300',1,data).ok,false));
test('missing mapping remains unknown',()=>{const r=describeBag([item()],{...data,products:[{...a,vehicleIds:null}]});assert.equal(r.lines[0].match,'unknown');assert.equal(r.subtotal,null);});
test('an empty mapping is a known nonmatch',()=>assert.equal(describeBag([item()],{...data,products:[{...a,vehicleIds:[]}]}).lines[0].match,'incompatible'));
test('adding the same product for another matching vehicle makes a second line',()=>{const r=addBagLine([item()],a.id,'touring-400',2,data);assert.equal(r.ok,true);assert.deepEqual(r.bag,[item(),item(2,'touring-400')]);});
test('line and product quantities remain capped',()=>assert.equal(addBagLine([item(9)],a.id,'street-155',2,data).ok,false));
test('can increase an existing line in a full twenty-line bag',()=>{const bag=[item(),...Array.from({length:19},(_,i)=>item(1,'street-155',`p-${i}`))];assert.equal(addBagLine(bag,a.id,'street-155',1,data).ok,true);assert.equal(addBagLine(bag,b.id,'road-300',1,data).ok,false);});
test('line key includes its own vehicle',()=>assert.notEqual(lineKey(a.id,'street-155'),lineKey(a.id,'touring-400')));
test('subtotal is integer VND for the loaded catalog',()=>{const r=describeBag([item(2),item(1,'road-300',b.id)],data);assert.equal(r.count,3);assert.equal(r.subtotal,7800000);assert.equal(r.needsReview,false);});
test('global vehicle selection never rewrites line vehicle',()=>{const bag=[item(2)];const r=describeBag(bag,{...data,vehicleId:'road-300'});assert.equal(r.lines[0].match,'compatible');assert.equal(r.lines[0].vehicleLabel,'Demo Moto Street 155 · 2022');assert.deepEqual(bag,[item(2)]);});
test('price reflects catalog, never stored unitPrice',()=>{const r=describeBag([{...item(2),unitPrice:1}],{...data,products:[{...a,price:3000000}]});assert.equal(r.subtotal,6000000);});
test('unavailable product makes total review-needed rather than a misleading partial sum',()=>{const r=describeBag([item(),item(1,'road-300',b.id)],{...data,products:[b]});assert.equal(r.subtotal,null);assert.equal(r.needsReview,true);assert.equal(r.lines.length,2);});
test('inactive product remains visible for removal, cannot increase',()=>{const r=describeBag([item(2)],{...data,products:[{...a,active:false}]});assert.equal(r.lines[0].canIncrease,false);assert.equal(r.subtotal,null);});
for(const options of [{loading:true},{error:'offline'}])test(`catalog ${JSON.stringify(options)} is not trusted`,()=>assert.equal(describeBag([item()],data,options).subtotal,null));
test('empty cart is honestly zero',()=>{const r=describeBag([],data);assert.equal(r.subtotal,0);assert.equal(r.count,0);assert.equal(r.needsReview,false);});
test('invalid item may be reduced',()=>assert.equal(changeBagQuantity([item(3)],a.id,'street-155',2,{...data,products:[]}).ok,true));
test('invalid item may not be increased',()=>assert.equal(changeBagQuantity([item()],a.id,'street-155',2,{...data,products:[]}).ok,false));
test('quantity is limited to 1–10, removal is an explicit operation',()=>{for(const q of [0,11,-1,2.5,'2'])assert.equal(changeBagQuantity([item()],a.id,'street-155',q,data).ok,false);});
test('remove only the exact product/vehicle line',()=>assert.deepEqual(removeBagLine([item(),item(2,'touring-400')],a.id,'street-155').bag,[item(2,'touring-400')]));
test('stale remove is a no-op failure, never removes other lines',()=>assert.equal(removeBagLine([item()],b.id,'road-300').ok,false));
test('two synchronous adds merge before React can render',()=>{const state=createCartState([]);state.add(a.id,'street-155',2,data);state.add(a.id,'street-155',3,data);assert.deepEqual(state.read(),[item(5)]);});
test('same-frame cap is respected by synchronous buffer',()=>{const state=createCartState([item(9)]);assert.equal(state.add(a.id,'street-155',1,data).ok,true);assert.equal(state.add(a.id,'street-155',1,data).ok,false);assert.equal(state.read()[0].quantity,10);});
test('same-frame different vehicles stay separate',()=>{const state=createCartState([]);state.add(a.id,'street-155',1,data);state.add(a.id,'touring-400',1,data);assert.equal(state.read().length,2);});
test('functional legacy setBag reads newest committed buffer',()=>{const state=createCartState([]);state.add(a.id,'street-155',2,data);state.replace(b=>b.map(i=>({...i,quantity:i.quantity+1})));assert.equal(state.read()[0].quantity,3);});
test('replace empty prevents stale adds resurrecting old rows',()=>{const state=createCartState([item()]);state.replace([]);state.add(b.id,'road-300',1,data);assert.deepEqual(state.read(),[item(1,'road-300',b.id)]);});
test('snapshots are immutable and cannot be changed from consumers',()=>{const state=createCartState([item()]);assert.throws(()=>{state.read()[0].quantity=10;});assert.throws(()=>state.read().push(item()));});
test('failed transactions do not mutate buffer identity',()=>{const state=createCartState([item(10)]),old=state.read();state.add(a.id,'street-155',1,data);assert.equal(state.read(),old);});
test('new drawer contains no GLB renderer or auto checkout call',async()=>{const s=await read('frontend/src/shop/cart/CartDrawer.jsx');assert.doesNotMatch(s,/from ['"](?:three|@react-three)|createOrder\s*\(/);assert.match(s,/to="\/bag"/);assert.match(s,/data-cart-dialog/);});
test('store retains loader readiness and uses synchronous cart hook',async()=>{const s=await read('frontend/src/shop/useStore.jsx');assert.match(s,/useCartState\(readCart\)/);assert.match(s,/cartRequest, openCart, closeCart/);assert.match(s,/if \(!result\.ok\)/);});
test('header retains bag href, keyboard and modified-click fallback',async()=>{const s=await read('frontend/src/shop/StoreApp.jsx');assert.match(s,/aria-controls="dth-cart-drawer"/);assert.match(s,/store\.openCart\(event\.currentTarget\)/);assert.match(s,/<CartDrawer \/>/);});
test('QuickView closes only after successful add with a latch',async()=>{const s=await read('frontend/src/shop/catalog/components/QuickView.jsx');assert.match(s,/if \(cartAddPending\.current\) return/);assert.match(s,/cartAddPending\.current = true/);assert.match(s,/shared cart waits/);});
