import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { CATEGORIES, fitment, filterProducts, normalizeItems, quoteOrder, validateProduct, validateRegistration } from '../shared/domain.mjs';
const data = JSON.parse(await readFile(new URL('../shared/catalog.json', import.meta.url), 'utf8'));
const p = data.products[0], vehicle = data.vehicles.find(v => p.vehicleIds.includes(v.id));
const item = { productId: p.id, vehicleId: vehicle.id, quantity: 2 };
test('catalog contains exactly 20 unique active demo products', () => { assert.equal(data.products.length, 20); assert.equal(new Set(data.products.map(p => p.id)).size, 20); assert.ok(data.products.every(p => p.demoOnly && p.active)); });
test('five supported categories, four products in each', () => { for (const c of CATEGORIES) assert.equal(data.products.filter(p => p.category === c).length, 4); });
test('eight unique fictional demo vehicles', () => { assert.equal(new Set(data.vehicles.map(v => v.id)).size, 8); assert.ok(data.vehicles.every(v => v.demoOnly && v.make.startsWith('Demo '))); });
test('all compatibility references resolve', () => { for (const product of data.products) for (const id of product.vehicleIds) assert.ok(data.vehicles.some(v => v.id === id)); });
test('every product points at an existing valid GLB and preview file', async () => {
  for (const product of data.products) {
    const base = new URL('../frontend/public/', import.meta.url);
    const glb = await readFile(new URL(product.modelUrl.slice(1), base));
    assert.equal(glb.toString('ascii', 0, 4), 'glTF'); assert.equal(glb.readUInt32LE(4), 2); assert.equal(glb.readUInt32LE(8), glb.length);
    assert.ok((await stat(new URL(product.imageUrl.slice(1), base))).size > 1000);
  }
});
test('unselected vehicle is not compatible', () => assert.equal(fitment(p, '', data.vehicles).status, 'unselected'));
test('unknown vehicle is not compatible', () => assert.equal(fitment(p, 'unknown-2026', data.vehicles).status, 'unknown'));
test('known matching vehicle is compatible', () => assert.equal(fitment(p, vehicle.id, data.vehicles).status, 'compatible'));
test('known unmatched vehicle is incompatible', () => assert.equal(fitment(p, data.vehicles.find(v => !p.vehicleIds.includes(v.id)).id, data.vehicles).status, 'incompatible'));
test('missing mappings are unknown, not compatible', () => assert.equal(fitment({ ...p, vehicleIds: undefined }, vehicle.id, data.vehicles).status, 'unknown'));
test('vehicle filter does not return mismatches', () => assert.ok(filterProducts(data.products, { vehicleId: vehicle.id }, data.vehicles).every(p => p.vehicleIds.includes(vehicle.id))));
test('unknown vehicle filter has no results', () => assert.equal(filterProducts(data.products, { vehicleId: 'unknown' }, data.vehicles).length, 0));
test('empty filters expose all 20 products', () => assert.equal(filterProducts(data.products).length, 20));
test('search ignores case and trims whitespace', () => assert.equal(filterProducts(data.products, { search: ' APEX ' }).length, 5));
test('category filter respects supported category', () => assert.equal(filterProducts(data.products, { category: 'mirrors' }).length, 4));
test('maximum price is inclusive', () => assert.ok(filterProducts(data.products, { maxPrice: 1000000 }).every(p => p.price <= 1000000)));
test('inactive products are excluded from browsing', () => assert.equal(filterProducts([{ ...p, active: false }]).length, 0));
test('empty cart is rejected', () => assert.throws(() => normalizeItems([]), /between 1 and 20/));
test('non-array cart is rejected', () => assert.throws(() => normalizeItems({}), /between 1 and 20/));
test('negative quantity is rejected', () => assert.throws(() => normalizeItems([{ ...item, quantity: -1 }]), /Quantity/));
test('fractional quantity is rejected', () => assert.throws(() => normalizeItems([{ ...item, quantity: 1.5 }]), /Quantity/));
test('numeric-string quantity is rejected', () => assert.throws(() => normalizeItems([{ ...item, quantity: '2' }]), /Quantity/));
test('NaN quantity is rejected', () => assert.throws(() => normalizeItems([{ ...item, quantity: NaN }]), /Quantity/));
test('more than ten per line is rejected', () => assert.throws(() => normalizeItems([{ ...item, quantity: 11 }]), /Quantity/));
test('more than twenty lines is rejected', () => assert.throws(() => normalizeItems(Array(21).fill(item)), /between 1 and 20/));
test('duplicates are merged deterministically', () => assert.deepEqual(normalizeItems([item, item]), [{ ...item, quantity: 4 }]));
test('duplicates cannot bypass quantity cap', () => assert.throws(() => normalizeItems([{ ...item, quantity: 6 }, { ...item, quantity: 6 }]), /Maximum quantity/));
test('object injection in product ID is rejected', () => assert.throws(() => normalizeItems([{ ...item, productId: { $ne: null } }]), /Invalid product ID/));
test('missing vehicle on a cart line is rejected', () => assert.throws(() => normalizeItems([{ ...item, vehicleId: '' }]), /Choose a demo vehicle/));
test('server quote ignores supplied prices and totals', () => { const q = quoteOrder([{ ...item, price: 1, unitPrice: 1, total: 1 }], data.products, data.vehicles); assert.equal(q.total, p.price * 2); assert.equal(q.paymentStatus, 'simulated'); });
test('quote blocks incompatible vehicles', () => assert.throws(() => quoteOrder([{ ...item, vehicleId: data.vehicles.find(v => !p.vehicleIds.includes(v.id)).id }], data.products, data.vehicles), /does not match/));
test('quote blocks unknown vehicles', () => assert.throws(() => quoteOrder([{ ...item, vehicleId: 'missing-2026' }], data.products, data.vehicles), /does not match/));
test('quote rejects disabled products', () => assert.throws(() => quoteOrder([item], [{ ...p, active: false }], data.vehicles), /no longer available/));
test('quote rejects removed products', () => assert.throws(() => quoteOrder([item], [], data.vehicles), /no longer available/));
test('quote rejects fractional catalog price', () => assert.throws(() => quoteOrder([item], [{ ...p, price: 1.1 }], data.vehicles), /Invalid catalog price/));
test('normalized registration lowercases email', () => assert.deepEqual(validateRegistration({ email: ' User@Example.test ', password: 'demo-password-123' }), { email: 'user@example.test', password: 'demo-password-123' }));
test('registration rejects missing/invalid email', () => assert.throws(() => validateRegistration({ email: 'invalid', password: 'demo-password-123' }), /valid email/));
test('registration rejects short password', () => assert.throws(() => validateRegistration({ email: 'user@example.test', password: 'short' }), /12 and 128/));
test('registration strips a requested admin role', () => assert.equal(validateRegistration({ email: 'user@example.test', password: 'demo-password-123', role: 'admin' }).role, undefined));
test('valid catalog entry passes admin validation', () => assert.equal(validateProduct(p, data.vehicles).id, p.id));
test('admin product rejects arbitrary model URLs', () => assert.throws(() => validateProduct({ ...p, modelUrl: 'https://evil.example/asset.glb' }, data.vehicles), /local/));
test('admin product rejects traversal', () => assert.throws(() => validateProduct({ ...p, modelUrl: '/models/../private.glb' }, data.vehicles), /local/));
test('admin product rejects negative prices', () => assert.throws(() => validateProduct({ ...p, price: -10 }, data.vehicles), /positive integer/));
test('admin product rejects unknown fitment IDs', () => assert.throws(() => validateProduct({ ...p, vehicleIds: ['unknown'] }, data.vehicles), /known demo vehicles/));
test('validated models cannot claim real fitment', () => assert.equal(validateProduct({ ...p, demoOnly: false }, data.vehicles).demoOnly, true));
