import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { NVX_IDS, NVX_VEHICLES, NVX_DEMO_RECIPES, isNVXId, nvxVehicleQuery, publishedNVXVehicles, vehicleLabel, assertNVXCatalog, buildNVXDemoCatalog } from '../shared/nvx.mjs';
import { matchingNVXParts, initialNVXSelection, nvxOptions, validLocalModel } from '../frontend/src/shop/garage/nvx.logic.mjs';
import { animateNVXEntry } from '../frontend/src/shop/garage/nvxMotion.mjs';
import { fitment, normalizeItems, quoteOrder } from '../shared/domain.mjs';
import { quoteCart } from '../shared/cartQuote.mjs';
import { makeNVXBaselineFixture } from './nvx-fixtures.mjs';
const base = makeNVXBaselineFixture(), catalog = buildNVXDemoCatalog(base);
const [v1, v2, v3] = NVX_IDS;
const line = (vehicleId = v1, productId = 'apex-suspension', quantity = 1) => ({ productId, vehicleId, quantity });
test('exactly NVX V1 V2 V3; no year property or fabricated year value', () => {
  assert.deepEqual(NVX_VEHICLES.map(v => v.model), ['NVX V1', 'NVX V2', 'NVX V3']);
  assert.ok(NVX_VEHICLES.every(v => v.make === 'Yamaha' && !Object.hasOwn(v, 'year')));
});
test('IDs are stable, distinct, immutable', () => { assert.equal(new Set(NVX_IDS).size, 3); assert.ok(Object.isFrozen(NVX_IDS) && NVX_VEHICLES.every(Object.isFrozen)); });
for (const invalid of ['', 'nvx-v4', 'street155-2022', 'NVX V1', null, {}, 2023]) test(`invalid selection rejected: ${JSON.stringify(invalid)}`, () => assert.equal(isNVXId(invalid), false));
test('NVX labels never append undefined or year', () => { assert.equal(vehicleLabel({ ...NVX_VEHICLES[1], year: 2024 }), 'Yamaha NVX V2'); assert.equal(vehicleLabel(null), ''); });
test('legacy receipt labels can retain historical year', () => assert.equal(vehicleLabel({ make: 'Demo Moto', model: 'Street 155', year: 2023 }), 'Demo Moto Street 155 · 2023'));
test('public versions are not invented before DB provisioning', () => { assert.deepEqual(publishedNVXVehicles([]), []); assert.throws(() => assertNVXCatalog({ products: [], vehicles: [] })); });
test('published versions ignore historical vehicles and are ordered', () => assert.deepEqual(publishedNVXVehicles([...NVX_VEHICLES].reverse().concat([{ id: 'old' }])), [...NVX_VEHICLES]));
test('wrong names for known IDs do not count as provisioned', () => assert.equal(publishedNVXVehicles([{ ...NVX_VEHICLES[0], model: 'Something else' }]).length, 0));
test('database scope cannot be broadened through query operators', () => { assert.deepEqual(nvxVehicleQuery([v2, 'street155-2022', { $ne: null }]), { id: { $in: [v2] } }); assert.deepEqual(nvxVehicleQuery({ $ne: null }), { id: { $in: [] } }); });
test('query callers cannot mutate the shared allowlist', () => { const q = nvxVehicleQuery(); q.id.$in.pop(); assert.equal(NVX_IDS.length, 3); });
test('catalog projection does not mutate baseline assets/prices/names', () => { const before = structuredClone(base); buildNVXDemoCatalog(base); assert.deepEqual(base, before); catalog.products.forEach((p, i) => { const { vehicleIds, ...rest } = p; const { vehicleIds: old, ...original } = base.products[i]; assert.deepEqual(rest, original); }); });
test('20 explicit synthetic mapping recipes; not a claim about real compatibility', () => { assert.equal(NVX_DEMO_RECIPES.length, 20); assert.ok(catalog.demoOnly); });
test('catalog projection is idempotent', () => assert.deepEqual(buildNVXDemoCatalog(catalog), catalog));
test('custom mappings are not inferred/replaced', () => { const changed = structuredClone(base); changed.products[0].vehicleIds = ['custom']; assert.deepEqual(buildNVXDemoCatalog(changed).products[0].vehicleIds, ['custom']); });
test('non-demo products are never auto-mapped', () => { const changed = structuredClone(base); changed.products[0].demoOnly = false; assert.deepEqual(buildNVXDemoCatalog(changed).products[0].vehicleIds, changed.products[0].vehicleIds); });
for (const id of NVX_IDS) test(`${id}: 10 matches in the synthetic test fixture`, () => assert.equal(matchingNVXParts(catalog.products, catalog.vehicles, id).length, 10));
test('invalid/hidden/unavailable prices do not inflate displayed demo counts', () => { const ps = catalog.products.map(p => ({ ...p, active: false })); assert.equal(matchingNVXParts(ps, catalog.vehicles, v1).length, 0); });
test('version cards expose only provisioned choices', () => { const options = nvxOptions(catalog.products, [NVX_VEHICLES[1]]); assert.deepEqual(options.map(o => o.available), [false, true, false]); });
test('saved valid version wins; stale defaults never map to an NVX implicitly', () => { assert.equal(initialNVXSelection(catalog.vehicles, v2), v2); assert.equal(initialNVXSelection([], 'street155-2022'), ''); });
test('studio assets are local GLB only', () => { assert.ok(validLocalModel(catalog.products[0])); for (const url of ['https://x/a.glb', '/models/../bad.glb', '/models/a.mp4', 'javascript:alert(1)']) assert.equal(validLocalModel({ modelUrl: url }), false); });
test('each version is a distinct fitment identity', () => { assert.equal(fitment(catalog.products[0], v1, catalog.vehicles).status, 'compatible'); assert.equal(fitment(catalog.products[0], v2, catalog.vehicles).status, 'incompatible'); });
test('old cart is retained but invalid, not silently retargeted', () => { const items = [line('street155-2022')]; const before = structuredClone(items); const q = quoteCart(items, catalog.products, catalog.vehicles); assert.equal(q.valid, false); assert.equal(q.lines[0].status, 'unknown'); assert.deepEqual(items, before); });
test('mixed NVX cart uses per-line versions, never a global override', () => { const items = [line(v1), line(v2, 'vector-suspension'), line(v3, 'touring-suspension')]; const q = quoteCart(items, catalog.products, catalog.vehicles); assert.ok(q.valid); assert.deepEqual(q.lines.map(l => l.vehicleId).sort(), [...NVX_IDS].sort()); });
test('no year in quote labels', () => assert.equal(quoteCart([line()], catalog.products, catalog.vehicles).lines[0].vehicleLabel, 'Yamaha NVX V1'));
test('quote sums server catalog prices, not supplied prices', () => { const q = quoteCart([{ ...line(v1, 'apex-suspension', 2), price: 1, total: 1 }], catalog.products, catalog.vehicles); assert.equal(q.total, catalog.products[0].price * 2); });
test('price edit invalidates previous quote fingerprint', () => { const a = quoteCart([line()], catalog.products, catalog.vehicles); const ps = structuredClone(catalog.products); ps[0].price++; assert.notEqual(quoteCart([line()], ps, catalog.vehicles).fingerprint, a.fingerprint); });
test('retired NVX record invalidates quote rather than claiming fit', () => assert.equal(quoteCart([line()], catalog.products, catalog.vehicles.slice(1)).valid, false));
test('changing version can invalidate the same product', () => assert.throws(() => quoteOrder([line(v2)], catalog.products, catalog.vehicles)));
test('quantity and identity validation remain enforced', () => { assert.throws(() => normalizeItems([line(v1, 'apex-suspension', 11)])); assert.throws(() => normalizeItems([{ ...line(), vehicleId: { $ne: null } }])); });
test('reduced motion schedules zero entry animations', () => { let calls = 0; const root = { querySelectorAll: () => [{ animate() { calls++; } }] }; animateNVXEntry(root, false)(); assert.equal(calls, 0); });
test('entry animation is bounded; cleanup is idempotent', () => { const calls = [], cancels = []; const nodes = Array.from({ length: 10 }, () => ({ animate(frames, opts) { calls.push(opts); return { finished: Promise.resolve(), cancel() { cancels.push(1); } }; } })); const cancel = animateNVXEntry({ querySelectorAll: () => nodes }, true); assert.equal(calls.length, 6); assert.ok(calls.every(x => x.iterations === 1 && x.delay + x.duration < 650)); cancel(); cancel(); assert.equal(cancels.length, 6); });
test('unavailable WAAPI cannot break selection', () => { assert.doesNotThrow(() => animateNVXEntry(null)()); assert.doesNotThrow(() => animateNVXEntry({ querySelectorAll: () => [{ animate() { throw new Error('unsupported'); } }] })()); });
const actualFile = new URL('../shared/catalog.json', import.meta.url);
test('repository asset catalogue preserves every product field except approved fitment', { skip: !existsSync(actualFile) }, () => {
  const original = JSON.parse(readFileSync(actualFile, 'utf8')); const result = buildNVXDemoCatalog(original);
  assert.equal(result.vehicles.length, 3); assert.equal(result.products.length, original.products.length);
  result.products.forEach((p, i) => { const { vehicleIds, ...after } = p; const { vehicleIds: old, ...before } = original.products[i]; assert.deepEqual(after, before); });
});

test('foreign currency cannot inflate NVX match counts', () => { const ps = catalog.products.map(p => ({ ...p, currency: 'USD' })); assert.equal(matchingNVXParts(ps, catalog.vehicles, v1).length, 0); });
test('showcase prefers a version-specific part over a shared demo mapping', () => { for (const id of NVX_IDS) assert.deepEqual(matchingNVXParts(catalog.products, catalog.vehicles, id)[0].vehicleIds, [id]); });
