import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { webcrypto, createHash } from 'node:crypto';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { validate3DProfile,parse3DProfile,bind3DProfile,isLocalModelURL } from '../shared/product3dProfile.mjs';
import { APEX_PRODUCT_3D_PROFILE as APEX,selectProduct3DProfile } from '../frontend/src/shop/product/3d/assetProfiles.mjs';
import { inspectGLB,embeddedImageSize,sha256Bytes,fetchModelBytes,versionedModelURL } from '../frontend/src/shop/product/3d/modelValidation.mjs';
import { inspectProductGeometry,makePresentation,resolvePresentation,automaticCamera } from '../frontend/src/shop/product/3d/profileTransform.mjs';
import { createProfileInspection } from '../frontend/src/shop/product/3d/profileCamera.mjs';
import { createFocusedInspection } from '../frontend/src/shop/product/advanced/focus.logic.mjs';
import { permittedMode } from '../frontend/src/shop/product/advanced/study.logic.mjs';
import { attachStudyEffects } from '../frontend/src/shop/product/advanced/studyShaders.mjs';
import { frameDistance } from '../frontend/src/shop/product/inspection.logic.mjs';
const clone=x=>JSON.parse(JSON.stringify(x));
const product={id:'apex-suspension',modelUrl:APEX.asset.url};
const bytes=new Uint8Array(await readFile(new URL('../frontend/public/models/dth-demo/apex-suspension.glb',import.meta.url)));
const loader=new GLTFLoader();const parse=()=>loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
const approx=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} vs ${b}`);
const distance=(a,b)=>Math.hypot(...a.map((n,i)=>n-b[i]));
function rewriteJSON(input,mutate){const b=new DataView(input.buffer,input.byteOffset,input.byteLength),n=b.getUint32(12,true),json=JSON.parse(new TextDecoder().decode(input.subarray(20,20+n)));mutate(json);let j=new TextEncoder().encode(JSON.stringify(json));const padded=new Uint8Array(Math.ceil(j.length/4)*4).fill(32);padded.set(j);const tail=input.subarray(20+n),out=new Uint8Array(20+padded.length+tail.length),v=new DataView(out.buffer);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,out.length,true);v.setUint32(12,padded.length,true);v.setUint32(16,0x4e4f534a,true);out.set(padded,20);out.set(tail,20+padded.length);return out;}

function embeddedPNG(input,width,height) {
  const v=new DataView(input.buffer,input.byteOffset,input.byteLength),jl=v.getUint32(12,true),doc=JSON.parse(new TextDecoder().decode(input.subarray(20,20+jl)));
  const old=input.subarray(20+jl+8),png=new Uint8Array(24),pv=new DataView(png.buffer);png.set([137,80,78,71,13,10,26,10]);pv.setUint32(16,width);pv.setUint32(20,height);
  doc.images=[{mimeType:'image/png',bufferView:doc.bufferViews.length}];doc.bufferViews.push({buffer:0,byteOffset:old.length,byteLength:png.length});doc.buffers[0].byteLength=old.length+png.length;
  const raw=new TextEncoder().encode(JSON.stringify(doc)),json=new Uint8Array(Math.ceil(raw.length/4)*4).fill(32);json.set(raw);
  const out=new Uint8Array(28+json.length+old.length+png.length),d=new DataView(out.buffer);d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,out.length,true);d.setUint32(12,json.length,true);d.setUint32(16,0x4e4f534a,true);out.set(json,20);d.setUint32(20+json.length,old.length+png.length,true);d.setUint32(24+json.length,0x004e4942,true);out.set(old,28+json.length);out.set(png,28+json.length+old.length);return out;
}

// Strict data contract and identity binding.
test('bundled Apex profile is complete and has exact local asset SHA',()=>{const r=validate3DProfile(APEX);assert.equal(r.ok,true);assert.equal(createHash('sha256').update(bytes).digest('hex'),r.profile.asset.sha256);});
test('validated profile is deeply copied and frozen',()=>{const a=clone(APEX),r=validate3DProfile(a);a.transform.rotation[0]=1;assert.equal(r.profile.transform.rotation[0],0);assert.ok(Object.isFrozen(r.profile.hotspots[0].position));});
for(const v of [null,[],{},'config',4])test('invalid top level rejected '+JSON.stringify(v),()=>assert.equal(validate3DProfile(v).ok,false));
test('schema version must be exact numeric v1',()=>{for(const v of [2,'1',1.1]){const p=clone(APEX);p.schemaVersion=v;assert.equal(validate3DProfile(p).ok,false);}});
test('nested unknown executable fields are rejected',()=>{const p=clone(APEX);p.camera.onClick='alert(1)';assert.equal(validate3DProfile(p).ok,false);});
test('prototype and inherited objects are rejected',()=>{const p=clone(APEX);p.transform=Object.create({scale:1});assert.equal(validate3DProfile(p).ok,false);assert.equal(parse3DProfile(JSON.stringify(APEX).replace('"transform":{','"transform":{"__proto__":{},')).ok,false);});
test('getters are rejected without execution',()=>{const p=clone(APEX);let called=0;Object.defineProperty(p,'version',{get(){called++;return '1.0.0';}});assert.equal(validate3DProfile(p).ok,false);assert.equal(called,0);});
test('finite numbers and proper vector lengths required',()=>{for(const v of [[0,NaN,0],[Infinity,0,0],[0,0],[0,'0',0]]){const p=clone(APEX);p.transform.rotation=v;assert.equal(validate3DProfile(p).ok,false);}});
test('negative/zero/oversized scales are rejected, not silently coerced',()=>{for(const v of [0,-1,2,'1']){const p=clone(APEX);p.transform.scale=v;assert.equal(validate3DProfile(p).ok,false);}});
for(const u of ['https://evil.test/a.glb','//evil.test/a.glb','/models/../a.glb','/models/%2e%2e/a.glb','/models/a.glb?redirect=x','/models/a.gltf','/models/a.glb#x','/models/a\\b.glb'])test('unsafe URL rejected '+u,()=>assert.equal(isLocalModelURL(u),false));
test('bounded revision query accepted and replaced by exact profile SHA',()=>{assert.ok(isLocalModelURL(APEX.asset.url+'?v=rev-2'));assert.equal(versionedModelURL(APEX.asset.url+'?v=2',APEX),APEX.asset.url+'?v='+APEX.asset.sha256);});
test('profile registration cannot rebind another product',()=>{assert.equal(bind3DProfile(APEX,{...product,id:'another'},APEX.asset.sha256).profile,null);assert.equal(bind3DProfile(APEX,{...product,modelUrl:'/models/new.glb'},APEX.asset.sha256).profile,null);});
test('filename alone never applies transforms or annotations',()=>{const r=bind3DProfile(APEX,product,'a'.repeat(64));assert.equal(r.status,'asset-changed');assert.equal(r.profile,null);});
test('unavailable crypto degrades to automatic view',()=>{assert.equal(bind3DProfile(APEX,product,null).status,'unverified');});
test('only exact product, URL and bytes permit profile use',()=>{assert.equal(bind3DProfile(APEX,product,APEX.asset.sha256).status,'profile');});
test('unregistered products have no arbitrary Apex fallback',()=>{assert.equal(selectProduct3DProfile({id:'wheel',modelUrl:'/models/wheel.glb'}).candidate,null);});
test('duplicate registry entry fails closed',()=>{assert.equal(selectProduct3DProfile(product,[APEX,APEX]).status,'invalid-profile');});
test('profile document is bounded before parsing',()=>{assert.equal(parse3DProfile(' '.repeat(33000)).ok,false);assert.equal(parse3DProfile('not json').ok,false);});
test('duplicate or selector-injecting hotspot IDs are rejected',()=>{const p=clone(APEX);p.hotspots[1].id=p.hotspots[0].id;assert.equal(validate3DProfile(p).ok,false);p.hotspots[1].id='x"]';assert.equal(validate3DProfile(p).ok,false);});
test('hotspot count is bounded and cannot be enabled empty',()=>{const p=clone(APEX);p.hotspots=[];assert.equal(validate3DProfile(p).ok,false);p.modes.hotspots=false;assert.equal(validate3DProfile(p).ok,true);p.hotspots=Array(7).fill(clone(APEX.hotspots[0]));assert.equal(validate3DProfile(p).ok,false);});
test('capture dates must be real and generation is not silently marked as scanning',()=>{const p=clone(APEX);p.provenance.captureDate='2026-02-30';assert.equal(validate3DProfile(p).ok,false);p.provenance.captureDate=null;p.provenance.source='ai-generated';assert.equal(validate3DProfile(p).profile.provenance.source,'ai-generated');});
test('camera coincident with target and nonboolean mode flags are invalid',()=>{const p=clone(APEX);p.camera.presets.front.position=[0,0,0];assert.equal(validate3DProfile(p).ok,false);const q=clone(APEX);q.modes.surface='true';assert.equal(validate3DProfile(q).ok,false);});
test('Surface and Technical can be independently disabled by capabilities',()=>{assert.equal(permittedMode('surface',{effects:true,surface:false}),false);assert.equal(permittedMode('technical',{effects:true,technical:true}),true);assert.equal(permittedMode('technical',{effects:false,technical:true}),false);});

// Container, decode budget and download controls.
test('real bundled GLB preflights without altering bytes',()=>{const before=bytes.slice(),r=inspectGLB(bytes);assert.equal(r.triangles,8752);assert.equal(r.vertices,4646);assert.deepEqual(bytes,before);});
test('all twenty bundled products meet standard GLB preflight',async()=>{const c=JSON.parse(await readFile(new URL('../shared/catalog.json',import.meta.url),'utf8'));for(const p of c.products){const b=await readFile(new URL('../frontend/public'+p.modelUrl,import.meta.url));assert.ok(inspectGLB(b).triangles>0,p.id);}});
test('magic, version and declared byte length are enforced',()=>{for(const offset of [0,4,8]){const b=bytes.slice();b[offset]^=1;assert.throws(()=>inspectGLB(b));}});
test('truncated and excessive GLB rejected',()=>{assert.throws(()=>inspectGLB(bytes.slice(0,50)));assert.throws(()=>inspectGLB(bytes,{bytes:100}));});
test('external and data URI buffers are rejected before parser fetch',()=>{for(const uri of ['https://evil.test/bin','../../.env','data:application/octet-stream;base64,AAAA'])assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.buffers[0].uri=uri)),/Embed/);});
test('external texture source rejected before decode',()=>assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.images=[{uri:'https://evil.test/tex.png'}])),/embedded/));
test('Draco and KTX2 require a future decoder integration',()=>{for(const extension of ['KHR_draco_mesh_compression','KHR_texture_basisu'])assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.extensionsUsed=[extension])),/decoders/);});
test('unknown required extensions and malformed extensions rejected',()=>{assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.extensionsRequired=['VENDOR_unknown'])));assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.extensionsUsed=[{}])));});
test('animation/skin/sparse data is rejected for static product pipeline',()=>{for(const mutate of [j=>j.animations=[{}],j=>j.skins=[{}],j=>j.accessors[0].sparse={}])assert.throws(()=>inspectGLB(rewriteJSON(bytes,mutate)));});
test('huge accessor or decoded buffer declarations fail before decode',()=>{for(const mutate of [j=>j.accessors[0].count=2**30,j=>j.buffers[0].byteLength=2**30,j=>j.bufferViews[0].byteOffset=2**30])assert.throws(()=>inspectGLB(rewriteJSON(bytes,mutate)));});
test('accessor buffer spans and invalid indices rejected',()=>{assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.accessors[0].byteOffset=200000000)));assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.meshes[0].primitives[0].indices=999999)));});
test('cyclic nodes and multi-parent nodes rejected',()=>{assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>j.nodes[0].children=[0])),/Cyclic/);assert.throws(()=>inspectGLB(rewriteJSON(bytes,j=>{j.nodes[0].children=[1];j.nodes[2].children=[1];})),/parent/);});
test('oversized embedded PNG rejected by whole GLB preflight before decode',()=>{assert.throws(()=>inspectGLB(embeddedPNG(bytes,8192,4096)),/4096px/);});
test('preflight records embedded texture dimensions without decoding pixels',()=>assert.deepEqual(inspectGLB(embeddedPNG(bytes,512,1024)).textureDimensions,[[512,1024]]));
test('wrong image formats rejected instead of decoded as SVG',()=>assert.throws(()=>embeddedImageSize(new TextEncoder().encode('<svg/>'),'image/svg+xml')));
test('SHA matches Node crypto exactly; no subtle returns null',async()=>{assert.equal(await sha256Bytes(bytes,webcrypto.subtle),APEX.asset.sha256);assert.equal(await sha256Bytes(bytes,null),null);});
test('streamed byte cap stops a lying/absent Content-Length download',async()=>{let cancelled=false;const body=new ReadableStream({start(c){c.enqueue(new Uint8Array(6));c.enqueue(new Uint8Array(6));},cancel(){cancelled=true;}});await assert.rejects(()=>fetchModelBytes('/models/x.glb',{maximum:10,fetcher:async()=>new Response(body)}),/exceeds/);assert.equal(cancelled,true);});
test('declared oversized download is rejected and response cancelled',async()=>{let cancelled=false;const body=new ReadableStream({cancel(){cancelled=true;}});await assert.rejects(()=>fetchModelBytes('/models/x.glb',{maximum:10,fetcher:async()=>new Response(body,{headers:{'content-length':'11'}})}));assert.equal(cancelled,true);});
test('download preserves bytes, same-origin credentials and refuses redirects',async()=>{let options;const output=await fetchModelBytes('/models/x.glb',{fetcher:async(u,o)=>{options=o;return new Response(bytes);}});assert.deepEqual(output,bytes);assert.equal(options.credentials,'same-origin');assert.equal(options.redirect,'error');});
test('HTTP failure does not turn into a silent demo fallback',async()=>{await assert.rejects(()=>fetchModelBytes('/models/x.glb',{fetcher:async()=>new Response('not found',{status:404})}),/404/);});

// Model and hotspot coordinate contract.
test('verified Apex migrates three authored markers without changing default geometry',async()=>{const {scene}=await parse(),m=inspectProductGeometry(scene),p=makePresentation(m,APEX);assert.equal(p.hotspots.length,3);approx(p.radius,1.35);approx(p.camera.fov,36);for(const h of p.hotspots)assert.ok(distance(h.position,p.center)<=1.35*1.025);});
test('normalization, rotation and offset apply equally to points and displayed model',async()=>{const {scene}=await parse(),m=inspectProductGeometry(scene),p=clone(APEX);p.transform.rotation=[.2,.7,-.1];p.transform.offset=[.2,-.1,.1];p.modes.hotspots=false;const fit=makePresentation(m,p),matrix=new THREE.Matrix4().fromArray(fit.matrix),manual=new THREE.Vector3(...m.normalization.center).applyMatrix4(matrix);assert.ok(manual.distanceTo(new THREE.Vector3(...p.transform.offset))<1e-7);});
test('scan range contains all transformed bounding corners',async()=>{const {scene}=await parse(),m=inspectProductGeometry(scene),p=clone(APEX);p.transform.rotation=[0,0,Math.PI/2];p.modes.hotspots=false;const fit=makePresentation(m,p),matrix=new THREE.Matrix4().fromArray(fit.matrix);for(const x of [m.box.min.x,m.box.max.x])for(const y of [m.box.min.y,m.box.max.y])for(const z of [m.box.min.z,m.box.max.z]){const v=new THREE.Vector3(x,y,z).applyMatrix4(matrix);assert.ok(v.y>=fit.heightRange[0]-1e-8&&v.y<=fit.heightRange[0]+fit.heightRange[1]+1e-8);}});
test('measuring and making profile does not rewrite vertices, materials or node transforms',async()=>{const {scene}=await parse();scene.updateMatrixWorld(true);const nodes=[];scene.traverse(n=>{if(n.isMesh)nodes.push([n,n.matrix.elements.slice(),n.geometry.attributes.position.array.slice(),n.material]);});makePresentation(inspectProductGeometry(scene),APEX);for(const [n,m,v,mat]of nodes){assert.deepEqual(n.matrix.elements,m);assert.deepEqual(n.geometry.attributes.position.array,v);assert.equal(n.material,mat);}});
test('bad custom camera falls back to automatic framing and no hotspots',async()=>{const {scene}=await parse(),m=inspectProductGeometry(scene),p=clone(APEX);p.camera.presets.front.position=[0,0,.2];const r=resolvePresentation(m,{status:'profile',profile:p,reason:''});assert.equal(r.status,'spatial-profile-invalid');assert.equal(r.presentation.hotspots.length,0);approx(r.presentation.radius,1.35);});
test('a hotspot outside the actual geometry invalidates profile framing safely',async()=>{const {scene}=await parse(),m=inspectProductGeometry(scene),p=clone(APEX);p.hotspots[0].position=[100,0,0];assert.equal(resolvePresentation(m,{profile:p}).profile,null);});
test('changed bytes never activate old transform even with same filename',async()=>{const {scene}=await parse(),m=inspectProductGeometry(scene),p=clone(APEX);p.transform.rotation=[1,0,0];const result=resolvePresentation(m,bind3DProfile(p,product,'f'.repeat(64)));assert.deepEqual(result.presentation.rotation,[0,0,0]);assert.deepEqual(result.presentation.hotspots,[]);});
test('nonfinite positions and invalid runtime indices are rejected',()=>{for(const change of [m=>m.geometry.attributes.position.setX(0,NaN),m=>m.geometry.index.setX(0,999999)]){const root=new THREE.Group(),mesh=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());root.add(mesh);change(mesh);assert.throws(()=>inspectProductGeometry(root));mesh.geometry.dispose();mesh.material.dispose();}});
test('effect clones preserve texture/material ownership after profile normalization',async()=>{const {scene}=await parse(),measured=inspectProductGeometry(scene),p=makePresentation(measured,APEX),original=[];scene.traverse(n=>{if(n.isMesh)original.push([n,n.material,n.geometry]);});const fx=attachStudyEffects(scene,p.heightRange);assert.equal(fx.available,true);fx.update({surface:1,technical:0,progress:.4});fx.dispose();for(const[n,mat,g]of original){assert.equal(n.material,mat);assert.equal(n.geometry,g);}});

// Camera transitions: real math, no WebGL needed.
test('automatic camera matches original Step12.2 front/side/rear path',()=>{const a=createProfileInspection(5),b=createFocusedInspection(5);for(const cmd of ['side','rear','front']){a.command(cmd);b.command(cmd);for(let i=0;i<160;i++){a.tick(1/60);b.tick(1/60);}for(const k of ['theta','phi','radius'])approx(a.read()[k],b.read()[k]);}});
test('profile camera presets replace defaults without rebuilding the viewer',()=>{const config=automaticCamera();config.presets.side={position:[-5,1,0],target:[0,.2,0]};const c=createProfileInspection();assert.equal(c.configure(config),true);c.command('side');c.settle();approx(c.read().theta,-Math.PI/2);approx(c.readTarget()[1],.2);});
test('every interpolated frame remains outside the model sphere with moving focus',()=>{const config=automaticCamera(),c=createProfileInspection();c.configure(config);c.focus([.6,.4,.2]);for(let i=0;i<200;i++){const s=c.tick(1/60);assert.ok(s.radius-distance(c.readTarget(),config.center)>=2.05-1e-7);}c.command('rear');for(let i=0;i<200;i++){const s=c.tick(1/60);assert.ok(s.radius-distance(c.readTarget(),config.center)>=2.05-1e-7);}});
test('custom hotspot focus uses its authored camera and target',()=>{const c=createProfileInspection(),config=automaticCamera();c.configure(config);const pose={position:[4,.5,2],target:[.1,.2,0]};assert.ok(c.focus([.1,.3,0],true,pose));c.settle();assert.deepEqual(c.readTarget(),pose.target);approx(c.read().theta,Math.atan2(3.9,2));});
test('bad custom focus returns false without mutation',()=>{const c=createProfileInspection(),s=c.read();assert.equal(c.focus([0,0,0],true,{position:[0,0,0],target:[0,0,0]}),false);assert.deepEqual(c.read(),s);});
test('queued rotation and zoom commands accumulate and opposite nudges cancel',()=>{const c=createProfileInspection(5),s=c.target();for(let i=0;i<4;i++)c.command('right');approx(c.target().theta,s.theta+1.28);c.command('left');c.command('right');approx(c.target().theta,s.theta+1.28);});
test('fast named-view requests use latest destination only',()=>{const c=createProfileInspection(5);c.command('rear');c.tick(.04);c.command('side');c.command('front');for(let i=0;i<200;i++)c.tick(.02);approx(c.read().theta,.28);assert.equal(c.moving,false);});
test('Motion off settles one step; modal/drag cancellation preserves pose',()=>{const c=createProfileInspection(5);c.command('rear');c.tick(.03);const p=c.read();c.cancel();assert.deepEqual(c.tick(.03),p);c.command('side');assert.deepEqual(c.tick(0,{motion:false}),c.target());assert.equal(c.command('front',false),false);});
test('background frames, invalid dt and inactive camera are bounded',()=>{const a=createProfileInspection(5),b=createProfileInspection(5);assert.deepEqual(a.tick(100,{spin:true}),b.tick(.05,{spin:true}));const p=a.read();assert.deepEqual(a.tick(99,{enabled:false,spin:true}),p);assert.deepEqual(a.tick(NaN,{spin:true}),p);});
test('30, 60 and 120 Hz rotation pace remains equal',()=>{const result=[30,60,120].map(fps=>{const c=createProfileInspection(5);for(let i=0;i<fps;i++)c.tick(1/fps,{spin:true});return c.read().theta;});approx(result[0],result[1]);approx(result[1],result[2]);});
test('resize preserves zoom ratio and authored front direction',()=>{const c=createProfileInspection(5);c.command('side');c.command('in');c.settle();const p=c.read();c.reframe(8);approx(c.read().theta,p.theta);approx(c.read().radius/8,p.radius/5);});
test('camera configuration and snapshots cannot be mutated through callers',()=>{const c=createProfileInspection(),config=automaticCamera();c.configure(config);config.presets.front.position[0]=30;c.command('front');c.settle();approx(c.read().theta,.28);const p=c.readTarget();p[0]=99;assert.equal(c.readTarget()[0],0);});
test('uniform scale updates safe camera radius rather than letting zoom intersect geometry',async()=>{const {scene}=await parse(),measured=inspectProductGeometry(scene),p=clone(APEX);p.transform.scale=.7;p.modes.hotspots=false;p.camera.presets=automaticCamera(1.35*.7).presets;const fit=makePresentation(measured,p),c=createProfileInspection();c.configure(fit.camera);for(let i=0;i<100;i++)c.command('in');c.settle();assert.ok(c.read().radius>=fit.radius*1.5);});
test('runtime source consumes profile plan and contains no filename-only hotspot path',async()=>{const scene=await readFile(new URL('../frontend/src/shop/product/ProductDecisionScene.jsx',import.meta.url),'utf8');assert.match(scene,/useProfiledModel/);assert.match(scene,/presentation.heightRange/);assert.match(scene,/createProfileInspection/);assert.doesNotMatch(scene,/profileForURL|resolveHotspots/);});

test('hotspot array getters are rejected without being evaluated',()=>{const p=clone(APEX);let called=0;Object.defineProperty(p.hotspots,'0',{get(){called++;return APEX.hotspots[0];},enumerable:true});assert.equal(validate3DProfile(p).ok,false);assert.equal(called,0);});
