import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Box3, BoxGeometry, Group, Mesh, MeshStandardMaterial, Sphere } from 'three';
import { PRODUCT_VIEW, purchaseState, validatePurchase, validAccent, validModelUrl, validPrice, safeShopReturn, matchingPartsHref, productSpecs } from '../frontend/src/shop/product/productDecision.logic.mjs';
import { createInspection, frameDistance, sphereNormalization } from '../frontend/src/shop/product/inspection.logic.mjs';
const catalog = JSON.parse(await readFile(new URL('../shared/catalog.json', import.meta.url), 'utf8'));
const product = catalog.products.find(p => p.id === 'apex-suspension');
const vehicles = catalog.vehicles;
const vehicleId = product.vehicleIds.find(id => vehicles.some(v => v.id === id));
const mismatch = vehicles.find(v => !product.vehicleIds.includes(v.id)).id;
const make = patch => ({ product, products:catalog.products, vehicles, vehicleId, bag:[], quantity:1, ...patch });
const approx = (a,b,e=1e-7) => assert.ok(Math.abs(a-b)<e, `${a} != ${b}`);

test('known compatible mapping enables buying without geometry data', () => assert.equal(purchaseState(product,vehicleId,vehicles,[]).canAdd,true));
test('unselected vehicle cannot add', () => assert.equal(purchaseState(product,'',vehicles,[]).match.status,'unselected'));
test('missing vehicle remains unknown', () => assert.equal(purchaseState(product,'unknown-id',vehicles,[]).match.status,'unknown'));
test('missing compatibility remains unknown, not incompatible', () => assert.equal(purchaseState({...product,vehicleIds:null},vehicleId,vehicles,[]).match.status,'unknown'));
test('malformed mixed compatibility IDs fail closed', () => assert.equal(purchaseState({...product,vehicleIds:[vehicleId,{}]},vehicleId,vehicles,[]).canAdd,false));
test('known nonmatching mapping is incompatible', () => assert.equal(purchaseState(product,mismatch,vehicles,[]).match.status,'incompatible'));
for(const value of [NaN,Infinity,-1,0,1.5,'100',1000000001,null]) test(`invalid catalog price blocks buying: ${String(value)}`,()=>{assert.equal(validPrice(value),false);assert.equal(purchaseState({...product,price:value},vehicleId,vehicles,[]).canAdd,false);});
test('inactive product cannot add',()=>assert.equal(purchaseState({...product,active:false},vehicleId,vehicles,[]).canAdd,false));
test('existing quantity is scoped to product and its vehicle',()=>{const bag=[{productId:product.id,vehicleId,quantity:4},{productId:product.id,vehicleId:mismatch,quantity:6}]; const s=purchaseState(product,vehicleId,vehicles,bag);assert.equal(s.remaining,6);assert.equal(s.inBag,4);});
test('duplicate lines count towards the same ten-item limit',()=>assert.equal(purchaseState(product,vehicleId,vehicles,[{productId:product.id,vehicleId,quantity:6},{productId:product.id,vehicleId,quantity:4}]).canAdd,false));
test('malformed existing quantity fails closed',()=>assert.equal(purchaseState(product,vehicleId,vehicles,[{productId:product.id,vehicleId,quantity:-1}]).canAdd,false));
test('twenty different bag lines prohibit a new line but not an existing one',()=>{const bag=Array.from({length:20},(_,i)=>({productId:`x-${i}`,vehicleId,quantity:1}));assert.equal(purchaseState(product,vehicleId,vehicles,bag).full,true);bag[0]={productId:product.id,vehicleId,quantity:1};assert.equal(purchaseState(product,vehicleId,vehicles,bag).canAdd,true);});
test('validation reads current price from catalog, not stale product prop',()=>{const updated=catalog.products.map(p=>p.id===product.id?{...p,price:product.price+500}:p);const r=validatePurchase(make({products:updated}));assert.equal(r.quote.total,product.price+500);});
test('removed product rechecked at click time',()=>assert.throws(()=>validatePurchase(make({products:[]})),/no longer available/));
test('changed mapping rechecked at click time',()=>assert.throws(()=>validatePurchase(make({products:[{...product,vehicleIds:[]}]})),/not listed/));
for(const q of [0,-2,1.2,11,NaN,'2'])test(`quantity must be integer and bounded: ${q}`,()=>assert.throws(()=>validatePurchase(make({quantity:q})),/valid quantity/));
test('buy request preserves the bag and per-line vehicle values',()=>{const bag=[{productId:product.id,vehicleId,quantity:1}];const before=JSON.stringify(bag);validatePurchase(make({bag}));assert.equal(JSON.stringify(bag),before);});
test('valid purchase delegates total calculation to shared domain rules',()=>assert.equal(validatePurchase(make({quantity:2})).quote.total,product.price*2));
test('safe Shop return preserves filters and page',()=>assert.equal(safeShopReturn('/shop?q=apex&category=wheels&page=2'),'/shop?q=apex&category=wheels&page=2'));
for(const path of ['https://evil.test/shop','//evil.test/shop','/shopper','/shop/../account','/shop\\evil','/shop\n',null,{}])test(`reject unsafe return route ${JSON.stringify(path)}`,()=>assert.equal(safeShopReturn(path),'/shop'));
test('alternatives keeps all filters, removes page, forces match',()=>{const p=new URLSearchParams(matchingPartsHref('/shop?q=apex&max=9000000&category=wheels&sort=name&page=2&x=yes').split('?')[1]);assert.equal(p.get('fit'),'match');assert.equal(p.has('page'),false);assert.equal(p.get('q'),'apex');assert.equal(p.get('max'),'9000000');assert.equal(p.get('x'),'yes');assert.equal(p.get('category'),'wheels');});
test('material swatch accepts only six-digit colors',()=>{assert.equal(validAccent('#12Ab56'),'#12Ab56');assert.equal(validAccent('url(https://evil.test)'),'#647888');});
test('specs accept scalar values and do not render objects as text',()=>assert.deepEqual(productSpecs({Width:'demo',Count:2,Test:true,Nested:{}}),[['Width','demo'],['Count','2'],['Test','true']]));
test('valid local GLB with bounded version supported',()=>{assert.equal(validModelUrl('/models/products/part.glb?v=rev-2'),true);assert.equal(validModelUrl('/models/../a.glb'),false);assert.equal(validModelUrl('https://example.test/a.glb'),false);assert.equal(validModelUrl('/models/a.glb?url=bad'),false);});

test('normalization centers translated/scaled geometry without changing it',()=>{const group=new Group();const mesh=new Mesh(new BoxGeometry(2,5,3),new MeshStandardMaterial());mesh.position.set(7,2,-4);mesh.scale.set(2,3,1);group.add(mesh);group.updateMatrixWorld(true);const box=new Box3().setFromObject(group),sphere=box.getBoundingSphere(new Sphere());const before=mesh.matrixWorld.elements.slice();const n=sphereNormalization(sphere.center.toArray(),sphere.radius);for(let i=0;i<3;i++)approx((n.center[i]+n.offset[i])*n.scale,0);approx(sphere.radius*n.scale,PRODUCT_VIEW.radius);assert.deepEqual(mesh.matrixWorld.elements,before);mesh.geometry.dispose();mesh.material.dispose();});
for(const [c,r] of [[[0,0,0],0],[[0,0,0],NaN],[[0,Infinity,0],1],[[1,2],3]])test(`reject invalid bounds ${JSON.stringify(c)} ${r}`,()=>assert.throws(()=>sphereNormalization(c,r)));
test('narrow viewport moves camera farther out to prevent clipping',()=>assert.ok(frameDistance(300,600)>frameDistance(900,600)));
test('invalid canvas dimensions produce finite safe distance',()=>assert.ok(Number.isFinite(frameDistance(NaN,-1))));
test('all supported sizes fit the model sphere',()=>{for(const [w,h] of [[300,300],[320,600],[700,460],[1600,900]]){const d=frameDistance(w,h),v=PRODUCT_VIEW.fov*Math.PI/180,hf=2*Math.atan(Math.tan(v/2)*w/h);assert.ok(Math.sin(Math.min(v,hf)/2)*d>PRODUCT_VIEW.radius);}});
test('same-frame rotation commands accumulate',()=>{const c=createInspection(5),before=c.target().theta;for(let i=0;i<4;i++)c.command('right');approx(c.target().theta-before,1.28);});
test('zoom is clamped outside model radius',()=>{const c=createInspection(5);for(let i=0;i<100;i++)c.command('in');assert.equal(c.target().radius,c.limits().min);assert.ok(c.target().radius>PRODUCT_VIEW.radius);});
test('opposite commands cancel destinations',()=>{const c=createInspection(5),s=c.target();c.command('left');c.command('right');approx(c.target().theta,s.theta);});
test('named view replaces pending commands with latest request',()=>{const c=createInspection(5);c.command('rear');c.command('front');approx(c.target().theta,.28);});
test('transition never crosses the model center',()=>{const c=createInspection(5);c.command('rear');for(let i=0;i<100;i++)assert.ok(c.tick(1/60).radius>PRODUCT_VIEW.radius);assert.equal(c.moving,false);});
test('blocked commands never move the camera',()=>{const c=createInspection(5),s=c.read();assert.equal(c.command('rear',false),false);assert.deepEqual(c.read(),s);});
test('unknown/inherited command names are rejected',()=>{const c=createInspection(5);for(const key of ['toString','__proto__',{},'remove'])assert.equal(c.command(key),false);});
test('Motion off settles the pending destination in one step',()=>{const c=createInspection(5);c.command('side');assert.deepEqual(c.tick(0,{motion:false}),c.target());assert.equal(c.moving,false);});
test('drag cancellation preserves current rendered pose',()=>{const c=createInspection(5);c.command('rear');c.tick(.03);const s=c.read();c.cancel();assert.deepEqual(c.tick(.02),s);});
test('inactive scene does not advance spin',()=>{const c=createInspection(5),s=c.read();assert.deepEqual(c.tick(10,{enabled:false,spin:true}),s);});
test('background time cannot cause catch-up rotation',()=>{const a=createInspection(5),b=createInspection(5);assert.deepEqual(a.tick(99,{spin:true}),b.tick(.05,{spin:true}));});
test('spin period is frame-rate independent at 30 / 60 / 120 Hz',()=>{const results=[30,60,120].map(fps=>{const c=createInspection(5);for(let i=0;i<fps*2;i++)c.tick(1/fps,{spin:true});return c.read().theta;});approx(results[0],results[1]);approx(results[1],results[2]);});
test('resize preserves viewing angles and zoom ratio',()=>{const c=createInspection(5);c.command('side');c.command('in');c.settle();const s=c.read();c.reframe(8);approx(c.read().radius/8,s.radius/5);approx(c.read().theta,s.theta);});
test('pose snapshots are independent',()=>{const c=createInspection(5),a=c.read();a.radius=NaN;assert.ok(Number.isFinite(c.read().radius));});
test('route integration switches only the product renderer', async()=>{const app=await readFile(new URL('../frontend/src/shop/StoreApp.jsx',import.meta.url),'utf8');assert.match(app,/<ProductDecisionPage\s/);assert.match(app,/path="products\/:slug"/);assert.match(app,/path="bag"/);assert.match(app,/path="account"/);});
