import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { webcrypto } from 'node:crypto';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { createStudyClock, permittedMode, finiteDelta, STUDY, normalizeHotspot } from '../frontend/src/shop/product/advanced/study.logic.mjs';
import { createFocusedInspection } from '../frontend/src/shop/product/advanced/focus.logic.mjs';
import { attachStudyEffects, injectStudyShader, inspectStudySupport, technicalVertex, technicalFragment } from '../frontend/src/shop/product/advanced/studyShaders.mjs';
import { APEX_PROFILE, profileForURL, fingerprintGeometry, resolveHotspots } from '../frontend/src/shop/product/advanced/hotspots.mjs';
import { frameDistance, sphereNormalization } from '../frontend/src/shop/product/inspection.logic.mjs';
const caps={effects:true,hotspots:[{id:'spring'}]};
const approx=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
const fixture=()=>{const group=new THREE.Group();const mesh=new THREE.Mesh(new THREE.BoxGeometry(1,2,1),new THREE.MeshStandardMaterial({color:'#cccccc'}));group.add(mesh);return {group,mesh};};
const disposal=({group})=>group.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [].concat(o.material))m.dispose();});

test('Explore always available without optional metadata',()=>assert.equal(permittedMode('explore'),true));
for(const mode of ['surface','technical','hotspots','__proto__','toString',null,{},'random'])test(`mode denied without capabilities: ${String(mode)}`,()=>assert.equal(permittedMode(mode),false));
test('explicit capabilities unlock only supported effects',()=>{assert.equal(permittedMode('surface',caps),true);assert.equal(permittedMode('hotspots',caps),true);assert.equal(permittedMode('surface',{effects:'yes'}),false);});
test('fresh clock is full Explore and idle',()=>{const s=createStudyClock().read();assert.equal(s.mode,'explore');assert.equal(s.busy,false);assert.equal(s.progress,1);});
test('Technical is a finite scan, stops at the end',()=>{const c=createStudyClock();c.mode('technical',caps);for(let i=0;i<1000;i++)c.tick(1/60);assert.equal(c.read().progress,1);assert.equal(c.read().busy,false);assert.equal(c.read().technical,1);});
test('mode switches never enqueue old animations',()=>{const c=createStudyClock();c.mode('surface',caps);c.tick(.04);c.mode('technical',caps);c.mode('explore',caps);for(let i=0;i<200;i++)c.tick(.02);assert.equal(c.read().mode,'explore');assert.equal(c.read().surface,0);assert.equal(c.read().technical,0);assert.equal(c.read().running,false);});
test('same active mode is not replayed',()=>{const c=createStudyClock();c.mode('technical',caps);c.tick(.05);const s=c.read();assert.equal(c.mode('technical',caps),false);assert.deepEqual(c.read(),s);});
test('replay starts a single new scan',()=>{const c=createStudyClock();c.mode('technical',caps);c.tick(.05);for(let i=0;i<20;i++)c.replay();assert.equal(c.read().progress,0);assert.equal(c.read().running,true);});
test('scrub is clamped and stops autoplay',()=>{const c=createStudyClock();c.mode('technical',caps);c.scrub(.42);c.tick(.02);approx(c.read().progress,.42);assert.equal(c.read().running,false);c.scrub(-4);assert.equal(c.read().progress,0);c.scrub(4);assert.equal(c.read().progress,1);});
test('scrub rejects nonfinite input',()=>{const c=createStudyClock();c.mode('technical',caps);for(const v of [NaN,Infinity,null,'1'])assert.equal(c.scrub(v),false);});
test('reduced motion settles automatically to complete nonanimated state',()=>{const c=createStudyClock();c.mode('technical',caps);const s=c.tick(.03,{motion:false});assert.equal(s.progress,1);assert.equal(s.busy,false);assert.equal(c.replay(false),false);});
test('Motion off still permits explicit static manual scan positioning',()=>{const c=createStudyClock();c.mode('technical',caps,false);c.scrub(.33);assert.equal(c.tick(.03,{motion:false}).progress,.33);});
test('modal / inactive clock does not advance',()=>{const c=createStudyClock();c.mode('surface',caps);const s=c.read();assert.deepEqual(c.tick(30,{active:false}),s);});
test('long background delta is clamped, no catch-up scan',()=>{const a=createStudyClock(),b=createStudyClock();a.mode('technical',caps);b.mode('technical',caps);assert.deepEqual(a.tick(100),b.tick(.05));});
for(const bad of [NaN,Infinity,-1,null,'2'])test(`invalid frame delta is harmless ${String(bad)}`,()=>assert.equal(finiteDelta(bad),0));
test('scan pace is frame-rate independent 30/60/120Hz',()=>{const values=[30,60,120].map(fps=>{const c=createStudyClock();c.mode('technical',caps);for(let i=0;i<fps*2;i++)c.tick(1/fps);return c.read().progress;});approx(values[0],values[1]);approx(values[1],values[2]);});
test('reading clock does not expose mutable internal state',()=>{const c=createStudyClock();c.read().progress=-9;assert.equal(c.read().progress,1);});

test('focus point is normalized without changing original coordinates',()=>{const p=[1,2,3],fit={center:[1,1,3],scale:.5};assert.deepEqual(normalizeHotspot(p,fit),[0,.5,0]);assert.deepEqual(p,[1,2,3]);});
test('outside or invalid hotspot rejected',()=>{for(const p of [[10,0,0],[NaN,0,0],[1],null])assert.equal(normalizeHotspot(p,{center:[0,0,0],scale:1}),null);});
test('filename alone cannot unlock Apex hotspots',()=>{assert.equal(resolveHotspots(APEX_PROFILE,'wrong',{center:[0,0,0],scale:1}).length,0);assert.equal(profileForURL('/models/another/model.glb'),null);assert.equal(profileForURL('https://evil.test/a.glb'),null);});
test('version query allowed only on matching local known path',()=>{assert.equal(profileForURL(APEX_PROFILE.modelPath+'?v=2'),APEX_PROFILE);assert.equal(profileForURL(APEX_PROFILE.modelPath+'?foo=2'),null);});
test('full geometry fingerprint changes for vertex modification',async()=>{const f=fixture();const before=await fingerprintGeometry(f.group,webcrypto.subtle);f.mesh.geometry.attributes.position.setX(0,.5001);assert.notEqual(before,await fingerprintGeometry(f.group,webcrypto.subtle));disposal(f);});
test('fingerprint changes for authored parent transform',async()=>{const f=fixture();const before=await fingerprintGeometry(f.group,webcrypto.subtle);f.group.position.y=.01;assert.notEqual(before,await fingerprintGeometry(f.group,webcrypto.subtle));disposal(f);});
test('fingerprint ignores material colour and private technical overlays',async()=>{const f=fixture();const before=await fingerprintGeometry(f.group,webcrypto.subtle);const fx=attachStudyEffects(f.group,[-1,2]);f.mesh.material.color.set('#ff0000');assert.equal(before,await fingerprintGeometry(f.group,webcrypto.subtle));fx.dispose();disposal(f);});
test('no crypto support disables annotations, not normal viewing',async()=>{const f=fixture();assert.equal(await fingerprintGeometry(f.group,null),null);disposal(f);});
test('demo asset verifies against authored profile and pins stay in normalized sphere',async()=>{
 const bytes=await readFile(new URL('../frontend/public/models/dth-demo/apex-suspension.glb',import.meta.url));
 const gltf=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
 const hash=await fingerprintGeometry(gltf.scene,webcrypto.subtle);assert.equal(hash,APEX_PROFILE.geometrySHA256);
 const sphere=new THREE.Box3().setFromObject(gltf.scene).getBoundingSphere(new THREE.Sphere());
 const hs=resolveHotspots(APEX_PROFILE,hash,sphereNormalization(sphere.center.toArray(),sphere.radius));assert.equal(hs.length,3);
 assert.ok(hs.every(h=>Math.hypot(...h.position)<1.36));disposal({group:gltf.scene});
});
test('invalid authored metadata never yields partial hotspots',()=>{const profile={geometrySHA256:'a',hotspots:[null]};assert.deepEqual(resolveHotspots(profile,'a',{center:[0,0,0],scale:1}),[]);});

test('camera focuses smoothly and stays outside entire model sphere',()=>{const c=createFocusedInspection(5);c.focus([0,1.1,.08]);for(let i=0;i<400;i++){const pose=c.tick(1/60);assert.ok(pose.radius-Math.hypot(...c.readTarget())>=STUDY.minCameraClearance-1e-6);}assert.equal(c.moving,false);assert.ok(c.readTarget()[1]>0);});
test('rapid focus / zoom / preset uses final destination',()=>{const c=createFocusedInspection(5);c.focus([0,1,0]);c.command('in');c.command('rear');for(let i=0;i<200;i++)c.tick(.02);approx(c.readTarget()[1],0);approx(c.read().theta,Math.PI);});
test('reset removes focus offset',()=>{const c=createFocusedInspection(5);c.focus([.1,.8,0]);c.settle();c.command('reset');c.settle();assert.deepEqual(c.readTarget(),[0,0,0]);approx(c.read().theta,.28);});
test('focus invalid or blocked cannot move camera',()=>{const c=createFocusedInspection(5),s=c.read();for(const p of [null,[NaN,0,0],[10,0,0]])assert.equal(c.focus(p),false);assert.equal(c.focus([0,.4,0],false),false);assert.deepEqual(c.read(),s);});
test('inactive camera freezes both look-at and orbit',()=>{const c=createFocusedInspection(5);c.focus([0,1,0]);const s=c.read(),t=c.readTarget();assert.deepEqual(c.tick(.1,{enabled:false}),s);assert.deepEqual(c.readTarget(),t);});
test('focus cancellation preserves displayed pose',()=>{const c=createFocusedInspection(5);c.focus([.1,.8,0]);c.tick(.05);const s=c.read(),t=c.readTarget();c.cancel();c.tick(.05);assert.deepEqual(c.read(),s);assert.deepEqual(c.readTarget(),t);});
test('Motion off completes a pending focus in one frame',()=>{const c=createFocusedInspection(5);c.focus([.1,.8,0]);c.tick(.02,{motion:false});assert.equal(c.moving,false);approx(c.readTarget()[1],.8);});
test('camera focus snapshots are independent arrays',()=>{const c=createFocusedInspection(5);c.readTarget()[1]=9;assert.equal(c.readTarget()[1],0);});
test('many zoom commands cannot enter focused model',()=>{const c=createFocusedInspection(5);c.focus([0,1,0]);c.settle();for(let i=0;i<100;i++)c.command('in');c.settle();assert.ok(c.read().radius-Math.hypot(...c.readTarget())>=STUDY.minCameraClearance);});
test('camera presets accumulate rotation and reject inherited names',()=>{const c=createFocusedInspection(5);const s=c.target().theta;for(let i=0;i<4;i++)c.command('right');approx(c.target().theta-s,1.28);for(const n of ['toString','__proto__',{}])assert.equal(c.command(n),false);});
test('resize and focus keep finite bounded state',()=>{const c=createFocusedInspection(5);c.focus([.4,.8,0]);c.tick(.05);c.reframe(frameDistance(320,600));assert.ok(Number.isFinite(c.read().radius));assert.ok(c.read().radius>1.35);});

test('effects clone materials / overlay geometry and restore exact references',()=>{const f=fixture(),old=f.mesh.material,geom=f.mesh.geometry;const fx=attachStudyEffects(f.group,[-1,2]);assert.equal(fx.available,true);assert.notEqual(f.mesh.material,old);assert.equal(f.mesh.geometry,geom);assert.notEqual(fx.overlays[0].geometry,geom);fx.dispose();assert.equal(f.mesh.material,old);assert.equal(f.mesh.children.length,0);disposal(f);});
test('disposing optional effects never disposes source geometry, maps or material',()=>{const f=fixture();const texture=new THREE.Texture();f.mesh.material.map=texture;let count=0;for(const obj of [f.mesh.geometry,f.mesh.material,texture])obj.addEventListener('dispose',()=>count++);const fx=attachStudyEffects(f.group,[-1,2]);fx.dispose();fx.dispose();assert.equal(count,0);texture.dispose();disposal(f);});
test('private geometry and materials disposed once',()=>{const f=fixture(),fx=attachStudyEffects(f.group,[-1,2]);let count=0;fx.overlays[0].geometry.addEventListener('dispose',()=>count++);fx.dispose();fx.dispose();assert.equal(count,1);disposal(f);});
test('material textures retain original references and colour',()=>{const f=fixture();const t=new THREE.Texture();f.mesh.material.map=t;const old=f.mesh.material,colour=old.color.clone();const fx=attachStudyEffects(f.group,[-1,2]);assert.equal(f.mesh.material.map,t);assert.ok(old.color.equals(colour));fx.update({technical:1,surface:0,progress:.4});assert.ok(old.color.equals(colour));fx.dispose();t.dispose();disposal(f);});
test('technical overlay inactive in Explore',()=>{const f=fixture(),fx=attachStudyEffects(f.group,[-1,2]);assert.equal(fx.overlays[0].visible,false);fx.update({technical:1,surface:0,progress:.5});assert.equal(fx.overlays[0].visible,true);fx.update({technical:0,surface:1,progress:1});assert.equal(fx.overlays[0].visible,false);fx.dispose();disposal(f);});
test('geometry barycentrics are complete triangles',()=>{const f=fixture(),fx=attachStudyEffects(f.group,[-1,2]);const a=fx.overlays[0].geometry.attributes.dthBarycentric;for(let i=0;i<a.count;i++)assert.equal(a.getX(i)+a.getY(i)+a.getZ(i),1);fx.dispose();disposal(f);});
for(const flag of ['transparent','alphaTest','transmission','wireframe'])test(`nonstandard material ${flag} keeps ordinary viewer`,()=>{const f=fixture();f.mesh.material[flag]=flag==='alphaTest'?.5:true;const fx=attachStudyEffects(f.group,[-1,2]);assert.equal(fx.available,false);assert.equal(f.mesh.children.length,0);disposal(f);});
test('existing custom material shaders not overwritten',()=>{const f=fixture();f.mesh.material.onBeforeCompile=()=>{};assert.equal(inspectStudySupport(f.group).ok,false);disposal(f);});
test('basic unlit material not patched',()=>{const f=fixture();f.mesh.material.dispose();f.mesh.material=new THREE.MeshBasicMaterial();assert.equal(inspectStudySupport(f.group).ok,false);disposal(f);});
test('skinned and instanced geometry not incorrectly duplicated',()=>{const f=fixture();f.mesh.isSkinnedMesh=true;assert.equal(inspectStudySupport(f.group).ok,false);disposal(f);});
test('too many meshes rejects effect before allocation',()=>{const f=fixture();for(let i=0;i<STUDY.maxMeshes;i++)f.group.add(f.mesh.clone());assert.equal(inspectStudySupport(f.group).ok,false);f.mesh.geometry.dispose();f.mesh.material.dispose();});
test('standard material shader includes scan and preserves tone mapping chunks',()=>{const sh={uniforms:{},vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader};injectStudyShader(sh,{example:{value:1}});assert.match(sh.fragmentShader,/dthStudyPassed/);assert.match(sh.fragmentShader,/#include <tonemapping_fragment>/);assert.match(sh.vertexShader,/vDthStudyWorld/);assert.equal(sh.uniforms.example.value,1);});
test('missing shader anchor fails clearly instead of silent partial injection',()=>assert.throws(()=>injectStudyShader({uniforms:{},vertexShader:'',fragmentShader:''},{}),/shader anchor/));
test('technical shader is derivative-antialiased, finite and depth aware',()=>{assert.match(technicalFragment,/fwidth/);assert.match(technicalVertex,/modelMatrix/);assert.doesNotMatch(technicalFragment,/while\s*\(/);});
test('purchase logic and asset loader are not imported by study clock',async()=>{const source=await readFile(new URL('../frontend/src/shop/product/advanced/study.logic.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/quoteOrder|vehicleIds|add\(/);});
