import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { categoryPatch, countLabel, displayPrice, shopReturnFromLocation, compactFitLabel, hashTargetsDisclosure } from '../frontend/src/shop/ux17/commerce17.logic.mjs';
const categories = [{id:'wheels'},{id:'brakes'},{id:'mirrors'}];
const read = name => readFile(new URL(`../frontend/src/shop/${name}`,import.meta.url),'utf8');

test('category selection keeps other categories and resets page',()=>assert.deepEqual(categoryPatch(['brakes'],'wheels',categories),{category:['brakes','wheels'],page:1}));
test('toggle removes only the chosen category',()=>assert.deepEqual(categoryPatch(['wheels','brakes'],'wheels',categories),{category:['brakes'],page:1}));
test('all categories does not clear price/search/vehicle/sort',()=>assert.deepEqual(categoryPatch(['brakes'],'',categories),{category:[],page:1}));
test('duplicate category inputs are deduplicated',()=>assert.deepEqual(categoryPatch(['brakes','brakes'],'mirrors',categories),{category:['brakes','mirrors'],page:1}));
test('unknown categories cannot be selected',()=>assert.equal(categoryPatch([], 'scripts', categories),null));
test('invalid category lists do not throw',()=>assert.deepEqual(categoryPatch(null,'',categories),{category:[],page:1}));
test('selection input is not mutated',()=>{ const v=Object.freeze(['brakes']);categoryPatch(v,'wheels',categories);assert.deepEqual(v,['brakes']); });
for (const v of [0,1,10,200]) test(`real count ${v} is displayed`,()=>assert.equal(countLabel(v),String(v)));
for (const v of [null,NaN,Infinity,-1,1.5,'7',{}]) test(`invalid count ${String(v)} is not fabricated`,()=>assert.equal(countLabel(v),'—'));
for (const v of [0,1000,1_000_000_000]) test(`valid VND price ${v}`,()=>assert.equal(displayPrice({price:v,currency:'VND'}),v));
for (const v of [NaN,Infinity,-1,1.5,'1000',null,1_000_000_001]) test(`bad price ${String(v)} is not formatted`,()=>assert.equal(displayPrice({price:v}),null));
test('another currency is not relabelled as VND',()=>assert.equal(displayPrice({price:100,currency:'USD'}),null));
test('missing product has no price',()=>assert.equal(displayPrice(null),null));
test('legacy VND default remains displayable',()=>assert.equal(displayPrice({price:100}),100));
test('product link remembers the exact shop query',()=>assert.equal(shopReturnFromLocation({pathname:'/shop',search:'?q=coil&category=brakes&fit=all&page=2'}),'/shop?q=coil&category=brakes&fit=all&page=2'));
for (const p of ['//evil.test','/shopping','https://evil.test',null]) test(`non-shop return ${p} is rejected`,()=>assert.equal(shopReturnFromLocation({pathname:p,search:'?q=x'}),'/shop'));
test('malformed query does not form a new path',()=>assert.equal(shopReturnFromLocation({pathname:'/shop',search:'//evil.test'}),'/shop'));
test('count/caption do not assert real fitment',()=>assert.match(compactFitLabel('compatible','NVX V2'),/Demo match/));
for(const status of ['unknown',null,'unsupported']) test(`unknown status ${status} stays unverified`,()=>assert.equal(compactFitLabel(status),'Fit not verified'));
test('incompatible is never called a match',()=>assert.equal(compactFitLabel('incompatible'),'No match for selected vehicle'));
test('no vehicle requests selection',()=>assert.match(compactFitLabel('unselected'),/Choose/));
test('deep-linked disclosure opens only for its own ID',()=>{assert.equal(hashTargetsDisclosure('#dth-product-specs','dth-product-specs'),true);assert.equal(hashTargetsDisclosure('#dth-product-about','dth-product-specs'),false);});
test('invalid hash encoding is safe',()=>assert.equal(hashTargetsDisclosure('#%XX','dth-product-specs'),false));
test('encoded hash matches',()=>assert.equal(hashTargetsDisclosure('#dth%2Dproduct%2Dspecs','dth-product-specs'),true));

test('Shop integrates compact presentation without a second filter state',async()=>{const s=await read('catalog/ShopPage.jsx');assert.match(s,/data-shop-ux="17"/);assert.match(s,/patchShopQuery\(previous, patch\)/);assert.match(s,/<CategoryRail[^>]*onPatch=\{update\}/);assert.match(s,/<ShopDialog title="Refine your search"/);assert.doesNotMatch(s,/<aside[^>]*aria-label="Catalog filters"/);});
test('drawer retains its existing focus restoration',async()=>{const s=await read('catalog/ShopPage.jsx');assert.match(s,/restoreFocus=\{filterTrigger.current\}/);assert.match(s,/onChooseVehicle=\{openVehicle\}/);});
test('product and Quick view are distinct non-nested actions',async()=>{const s=await read('ux17/ShopProductCard.jsx');assert.match(s,/to=\{href\} state=\{\{ fromShop \}\}/);assert.match(s,/onQuickView\(product.id, event.currentTarget\)/);assert.doesNotMatch(s,/preventDefault\(|<canvas|<video/);});
test('changing NVX never changes bag or default account',async()=>{const s=await read('ux17/VehicleBar.jsx');assert.match(s,/store.setVehicle\(id\)/);assert.match(s,/fit: 'match', page: 1/);assert.doesNotMatch(s,/setBag|setUser|saveAccountVehicle|fetch\(/);});
test('real disclosures preserve their original anchor IDs',async()=>{const s=await read('product/ProductDecisionPage.jsx');for(const id of ['about','specs','fitment'])assert.match(s,new RegExp(`<Disclosure id="dth-product-${id}"`));assert.match(s,/Synthetic demo mappings only/);assert.match(s,/Simulated purchase/);});
test('purchase still uses validation and accepted store operation',async()=>{const s=await read('product/ProductDecisionPage.jsx');assert.match(s,/validatePurchase\(\{/);assert.match(s,/if \(!store.add\(checked.product, checked.vehicleId, checked.quantity\)\)/);assert.match(s,/blocked \|\| cooldown \|\| !state.available/);});
test('3D scene, readiness, failover and keyboard controls remain',async()=>{const s=await read('product/ProductMedia.jsx');for(const token of ['<Scene product={product}','onAssetReport={reportAsset}','PRODUCT_VIEW.timeoutMs','onKeyDown={keyboard}',"useState(!policy.compact && !policy.reduced && !policy.saveData)","imageMode()",'Retry 3D'])assert.ok(s.includes(token),token);assert.match(s,/<Disclosure id="dth-product-tools"/);assert.doesNotMatch(s,/<video/);});
test('basic view controls remain outside the advanced disclosure',async()=>{const s=await read('product/ProductMedia.jsx');assert.ok(s.indexOf('aria-label="3D view controls"')<s.indexOf('<Disclosure id="dth-product-tools"'));assert.ok(s.indexOf('aria-label="3D study mode"')>s.indexOf('<Disclosure id="dth-product-tools"'));});
test('disclosure has native semantics and removable hash listener',async()=>{const s=await read('ux17/Disclosure.jsx');assert.match(s,/<details /);assert.match(s,/<summary>/);assert.match(s,/removeEventListener\('hashchange'/);assert.doesNotMatch(s,/setInterval|setTimeout|dangerouslySetInnerHTML/);});
test('CSS scopes and motion opt-out remain',async()=>{const s=await read('ux17/commerce17.css');assert.match(s,/prefers-reduced-motion:reduce/);assert.match(s,/data-motion="off"/);assert.doesNotMatch(s,/\.dth-header|\[data-dth-ignition\]|(?:^|\n)\s*(?:html|body|canvas)\s*\{/);});
