import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { getPriceCeiling, readShopQuery, patchShopQuery, resetShopFilters, selectShopProducts, paginateProducts, previewSource, describeFit, clampZoom } from '../frontend/src/shop/catalog/catalog.logic.mjs';
import { SHOP_CONFIG } from '../frontend/src/shop/catalog/catalog.config.mjs';
const data = JSON.parse(await readFile(new URL('../shared/catalog.json', import.meta.url), 'utf8'));
const ceiling = getPriceCeiling(data.products);
const query = raw => readShopQuery(raw, ceiling);
const pick = (raw = '', id = '') => selectShopProducts(data.products, data.vehicles, id, query(raw));

test('default query includes all demo products; no old hardcoded maximum', () => assert.equal(pick().length, data.products.filter(p => p.active !== false).length));
test('price ceiling includes most expensive active product', () => assert.ok(ceiling >= Math.max(...data.products.map(p => p.price))));
test('price ceiling ignores inactive/invalid records', () => assert.equal(getPriceCeiling([{ price: 100001 }, { price: 1e8, active: false }, { price: NaN }]), 150000));
test('empty catalog has a valid slider ceiling', () => assert.equal(getPriceCeiling([]), 50000));
test('search is trimmed and case insensitive', () => assert.ok(pick('q=%20APEX%20').every(p => p.name.includes('Apex'))));
test('multiple search terms match name/category/finish regardless of order', () => assert.deepEqual(pick('q=graphite%20coilover').map(p => p.id).sort(), ['apex-suspension', 'studio-suspension']));
test('search can match product IDs', () => assert.deepEqual(pick('q=apex-wheels').map(p => p.id), ['apex-wheels']));
test('no search results produces no invented fallback', () => assert.equal(pick('q=does-not-exist').length, 0));
test('query length is bounded', () => assert.equal(query(`q=${'a'.repeat(500)}`).search.length, 160));
test('multiple selected categories use OR, then AND with other filters', () => assert.equal(pick('category=wheels&category=suspension&q=Apex').length, 2));
test('old Home single-category URLs remain compatible', () => assert.equal(pick('category=mirrors').length, 4));
test('comma-delimited categories and duplicates normalize', () => assert.deepEqual(query('category=wheels,suspension&category=wheels').categories, ['wheels','suspension']));
test('unknown category and sort are sanitized', () => { assert.deepEqual(query('category=unknown').categories, []); assert.equal(query('sort=random').sort, 'featured'); });
test('zero maximum price is not replaced by the default', () => { assert.equal(query('max=0').maxPrice, 0); assert.equal(pick('max=0').length, 0); });
test('negative price clamps to zero', () => assert.equal(query('max=-7').maxPrice, 0));
test('oversized max clamps to catalog ceiling', () => assert.equal(query('max=999999999').maxPrice, ceiling));
test('invalid or blank max returns ceiling', () => { for (const v of ['NaN','Infinity','']) assert.equal(query(`max=${v}`).maxPrice, ceiling); });
test('prices are filtered as numbers', () => assert.ok(pick('max=1000000').every(p => p.price <= 1000000)));
test('low price sort is ascending', () => { const a = pick('sort=price-low').map(p => p.price); assert.deepEqual(a, [...a].sort((x,y) => x-y)); });
test('high price sort is descending', () => { const a = pick('sort=price-high').map(p => p.price); assert.deepEqual(a, [...a].sort((x,y) => y-x)); });
test('name sort is deterministic', () => { const a = pick('sort=name').map(p => p.name); assert.deepEqual(a, [...a].sort((x,y) => x.localeCompare(y,'en'))); });
test('catalog source is not mutated by filtering or sorting', () => { const before = JSON.stringify(data.products); pick('sort=price-low'); assert.equal(JSON.stringify(data.products), before); });
test('inactive products are never returned', () => { const p = { ...data.products[0], active: false }; assert.equal(selectShopProducts([p], data.vehicles,'', query('')).length, 0); });
test('negative or non-finite prices are never returned', () => assert.equal(selectShopProducts([{...data.products[0],price:-1},{...data.products[0],price:NaN}],data.vehicles,'',query('')).length,0));
test('a selected vehicle defaults to matching only', () => { const id = data.vehicles[0].id; const parts = pick('',id); assert.equal(parts.length,5); assert.ok(parts.every(p => p.vehicleIds.includes(id))); });
test('show-all mode keeps mismatching records visible for labelled comparison', () => assert.equal(pick('fit=all',data.vehicles[0].id).length,20));
test('an unknown vehicle must not be treated as compatible', () => assert.equal(pick('','nonexistent').length,0));
test('unknown vehicle in show-all mode has unknown labels', () => { assert.equal(pick('fit=all','nonexistent').length,20); assert.equal(describeFit(data.products[0],'nonexistent',data.vehicles).status,'unknown'); });
test('missing compatibility data remains unknown', () => assert.equal(describeFit({...data.products[0],vehicleIds:undefined},data.vehicles[0].id,data.vehicles).status,'unknown'));
test('facet counts can ignore current category but retain fit/search/price', () => { const parts = selectShopProducts(data.products,data.vehicles,data.vehicles[0].id,query('category=wheels'),{ignoreCategories:true});assert.equal(parts.length,5); });
test('filter changes reset pagination and preserve unrelated params', () => { const p=patchShopQuery('page=3&sort=name&utm_source=test',{category:['brakes','wheels']});assert.equal(p.get('page'),null);assert.equal(p.get('sort'),'name');assert.equal(p.get('utm_source'),'test');assert.deepEqual(p.getAll('category'),['brakes','wheels']); });
test('pagination-only changes do not clear filters', () => { const p=patchShopQuery('category=brakes&q=apex',{page:2});assert.equal(p.get('q'),'apex');assert.equal(p.get('page'),'2'); });
test('reset retains fit mode and sort (vehicle lives in StoreProvider)', () => { const p=resetShopFilters('q=a&category=brakes&max=10&page=3&fit=all&sort=name');assert.equal(p.toString(),'fit=all&sort=name'); });
test('page size and last page are bounded', () => { const p=paginateProducts(pick(),99,9);assert.equal(p.page,3);assert.equal(p.from,19);assert.equal(p.to,20);assert.equal(p.items.length,2); });
test('empty results do not report a phantom item', () => { const p=paginateProducts([],2,9);assert.equal(p.from,0);assert.equal(p.to,0);assert.equal(p.page,1); });
test('invalid page inputs normalize', () => { for (const x of ['0','-5','oops','1.2','Infinity']) assert.equal(query(`page=${x}`).page,1); });
test('known demo asset gets a dedicated transparent preview', () => assert.equal(previewSource(data.products[0]),'/previews/shop-motion/apex-suspension.png'));
test('custom photo or custom model path is not overridden', () => { assert.equal(previewSource({...data.products[0],imageUrl:'/previews/custom.webp'}),'/previews/custom.webp'); assert.equal(previewSource({...data.products[0],modelUrl:'/models/updated.glb'}),data.products[0].imageUrl); });
test('preview override can be disabled', () => assert.equal(previewSource(data.products[0],false),data.products[0].imageUrl));
test('all 20 preview files exist after copying the update', async () => { for (const p of data.products) await access(new URL(`../frontend/public${previewSource(p)}`,import.meta.url)); });
test('image zoom is clamped and rounded', () => { assert.equal(clampZoom(-4),1);assert.equal(clampZoom(4),2);assert.equal(clampZoom(1.74999999),1.75); });
test('config preserves a small, adjustable motion budget', () => { assert.ok(SHOP_CONFIG.motion.hoverScale > 1 && SHOP_CONFIG.motion.hoverScale <= 1.3);assert.equal(SHOP_CONFIG.pageSize,9); });
test('Shop does not import Home/Canvas or alter existing Viewer3D', async () => { const source=await readFile(new URL('../frontend/src/shop/catalog/ShopPage.jsx',import.meta.url),'utf8');assert.ok(!source.includes('HeroScene'));assert.ok(!source.includes('@react-three')); });
test('dialogs use native modality and cleanup', async () => { const source=await readFile(new URL('../frontend/src/shop/catalog/components/ShopDialog.jsx',import.meta.url),'utf8');assert.ok(source.includes('showModal()'));assert.ok(source.includes('onCancel'));assert.ok(source.includes('previous.focus')); });
test('reduced-motion CSS and interaction hooks are present', async () => { const css=await readFile(new URL('../frontend/src/shop/catalog/ShopPage.module.css',import.meta.url),'utf8'); const hook=await readFile(new URL('../frontend/src/shop/catalog/hooks/useShopMotion.js',import.meta.url),'utf8');assert.ok(css.includes('prefers-reduced-motion:reduce'));assert.ok(hook.includes('animation.cancel()')); });
