import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { createSurfaceController, createSurfaceEngine, pointInCanvas, SURFACE_FX } from '../frontend/src/experience/story/effects/surfaceMotion.mjs';
import { attachSurfaceEffects, injectSurfaceShader } from '../frontend/src/experience/story/effects/surfaceShaders.mjs';
const gate={active:true,motion:true,blocked:false,pointerAllowed:true};
function setup(){const c=createSurfaceController(),e=createSurfaceEngine();e.start();return{c,e};}
function advance(e,c,seconds=3,fps=60,g=gate){for(let i=0;i<seconds*fps;i++)e.step(1/fps,g,c.getSnapshot(),1.2);return e.state;}

test('Controller snapshots remain stable until a valid change',()=>{const c=createSurfaceController(),s=c.getSnapshot();assert.equal(c.getSnapshot(),s);c.choose('surface');assert.equal(c.getSnapshot(),s);c.choose('reveal');assert.notEqual(c.getSnapshot(),s);});
test('Unknown/prototype-like effect modes are rejected',()=>{const c=createSurfaceController();for(const name of ['constructor','__proto__','x',null,{},1])assert.equal(c.choose(name),false);assert.equal(c.getSnapshot().mode,'surface');});
test('Controller listeners clean up and duplicate changes do not notify',()=>{const c=createSurfaceController();let n=0;const stop=c.subscribe(()=>n++);c.choose('reveal');c.choose('reveal');assert.equal(n,1);stop();c.choose('surface');assert.equal(n,1);assert.equal(c.listenerCount,0);});
test('Unsupported assets fall back to the complete surface',()=>{const c=createSurfaceController();c.choose('technical');c.supported(false);assert.equal(c.getSnapshot().mode,'surface');assert.equal(c.getSnapshot().supported,false);});
test('Pointer is converted relative to the actual canvas',()=>{assert.deepEqual(pointInCanvas(300,250,{left:100,top:50,width:400,height:400}),{x:0,y:0});});
test('Invalid/outside pointer events are ignored',()=>{for(const x of [NaN,Infinity,-20,1000])assert.equal(pointInCanvas(x,20,{left:0,top:0,width:200,height:200}),null);assert.equal(pointInCanvas(0,0,{left:0,top:0,width:0,height:100}),null);});
test('First load progresses from technical underlay to full material',()=>{const {c,e}=setup();e.step(0,gate,c.getSnapshot());assert.equal(e.state.level,0);advance(e,c);assert.equal(e.state.level,1);assert.equal(e.state.needsFrame,false);});
test('Entrance timing is independent of 30/60/120Hz',()=>{const values=[30,60,120].map(f=>{const{c,e}=setup();return advance(e,c,1,f).level;});assert.ok(Math.max(...values)-Math.min(...values)<1e-10);});
test('Full surface -> reveal dissolves while keeping a valid mask level',()=>{const{c,e}=setup();advance(e,c);c.choose('reveal');advance(e,c,2);assert.equal(e.state.level,0);assert.equal(e.state.mode,'reveal');assert.equal(e.state.scanning,true);});
test('First pointer entry never creates a phantom stroke',()=>{const{c,e}=setup();advance(e,c);c.choose('reveal');advance(e,c,2);e.move(.7,.4);e.step(1/60,gate,c.getSnapshot());assert.equal(e.state.pace,0);});
test('Moving pointer produces a bounded capsule history',()=>{const{c,e}=setup();c.choose('reveal');advance(e,c);e.move(-.7,0);e.step(1/60,gate,c.getSnapshot());for(let i=0;i<24;i++){e.move(-.7+i*.06,.2);e.step(1/60,gate,c.getSnapshot(),1.4);}assert.ok(e.state.pace>.1&&e.state.pace<=1);assert.ok(e.state.trail.every(Number.isFinite));assert.ok(e.state.bounds.every(Number.isFinite));});
test('Pointer trail memory is reused rather than allocated per frame',()=>{const{c,e}=setup();const a=e.state.trail;advance(e,c);c.choose('reveal');advance(e,c,10,120);assert.equal(e.state.trail,a);assert.equal(a.length,SURFACE_FX.samples*3);});
test('A resting pointer drains instead of leaving a permanent blob',()=>{const{c,e}=setup();c.choose('reveal');advance(e,c);e.move(-.8,0);e.step(1/60,gate,c.getSnapshot());e.move(.8,0);advance(e,c,.3);assert.ok(e.state.pace>.01);advance(e,c,3);assert.ok(e.state.pace<.001);});
test('Pointer exit fades and clears history',()=>{const{c,e}=setup();c.choose('reveal');advance(e,c);e.move(-.8,0);e.step(1/60,gate,c.getSnapshot());e.move(.8,0);advance(e,c,.2);e.leave();advance(e,c,3);assert.equal(e.state.pace,0);assert.ok(e.state.trail.every(n=>n===0));});
for(const change of [{active:false},{blocked:true}])test(`Activity gate freezes time/front and clears trail: ${JSON.stringify(change)}`,()=>{const{c,e}=setup();advance(e,c,.5);const before={...e.state};advance(e,c,2,60,{...gate,...change});assert.equal(e.state.time,before.time);assert.equal(e.state.level,before.level);assert.equal(e.state.needsFrame,false);});
test('Motion off during dissolve shows the complete surface immediately',()=>{const{c,e}=setup();advance(e,c);c.choose('reveal');advance(e,c,.3);advance(e,c,1,60,{...gate,motion:false});assert.equal(e.state.level,1);assert.equal(e.state.scanning,false);assert.equal(e.state.needsFrame,false);});
test('A touch/compact pointer cannot leave the product masked',()=>{const{c,e}=setup();advance(e,c);c.choose('reveal');advance(e,c,2,60,{...gate,pointerAllowed:false});assert.equal(e.state.level,1);assert.equal(e.state.mode,'surface');});
test('Rapid mode switching finishes at the last requested state',()=>{const{c,e}=setup();advance(e,c);for(const m of ['reveal','technical','surface','reveal','surface']){c.choose(m);advance(e,c,.1);}advance(e,c,3);assert.equal(e.state.mode,'surface');assert.equal(e.state.level,1);});
test('Replay starts one fresh reveal, without queuing old replays',()=>{const{c,e}=setup();advance(e,c);c.replay();e.step(0,gate,c.getSnapshot());assert.equal(e.state.level,0);advance(e,c,.2);c.replay();e.step(0,gate,c.getSnapshot());assert.equal(e.state.level,0);advance(e,c,3);assert.equal(e.state.level,1);});
test('Invalid and very large deltas never corrupt motion',()=>{const{c,e}=setup();for(const dt of [NaN,Infinity,-1,1000,undefined]){e.step(dt,gate,c.getSnapshot());assert.ok(Number.isFinite(e.state.time)&&Number.isFinite(e.state.level));}assert.ok(e.state.time<=.05);});
test('Stable full material does not request a perpetual effects render loop',()=>{const{c,e}=setup();advance(e,c);for(let i=0;i<10;i++)assert.equal(e.step(.016,gate,c.getSnapshot()).needsFrame,false);});
function fixture(mat=new THREE.MeshStandardMaterial()){const root=new THREE.Group(),geometry=new THREE.BoxGeometry(1,2,1),mesh=new THREE.Mesh(geometry,mat);mesh.position.set(.3,.1,0);root.add(mesh);return{root,geometry,mesh,mat};}
test('Surface masks inject into real Three.js standard shader anchors',()=>{const shader={uniforms:{},vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader};injectSurfaceShader(shader,{});assert.match(shader.vertexShader,/vDthClip=gl_Position/);assert.match(shader.fragmentShader,/totalEmissiveRadiance\+=uDthAccent/);assert.match(shader.fragmentShader,/dthSurface.x/);});
test('Unsupported shader source fails explicitly instead of silently dropping effect',()=>{assert.throws(()=>injectSurfaceShader({vertexShader:'x',fragmentShader:'y',uniforms:{}},{}),/Unsupported/);});
test('Effect clones material but never mutates the source color or geometry',()=>{const f=fixture(),old=f.mat.toJSON(),engine=createSurfaceEngine();const fx=attachSurfaceEffects(f.root,engine,[-1,2]);assert.ok(fx);assert.notEqual(f.mesh.material,f.mat);assert.equal(f.mesh.geometry,f.geometry);assert.deepEqual(f.mat.toJSON(),old);assert.equal(f.mesh.children.length,2);fx.dispose();assert.equal(f.mesh.material,f.mat);assert.equal(f.mesh.children.length,0);f.geometry.dispose();f.mat.dispose();});
test('Underlay and wire inherit the original mesh transform',()=>{const f=fixture();const fx=attachSurfaceEffects(f.root,createSurfaceEngine(),[-1,2]);f.root.rotation.y=.6;f.root.updateMatrixWorld(true);for(const child of f.mesh.children)assert.ok(child.matrixWorld.equals(f.mesh.matrixWorld));fx.dispose();});
test('Disposal is idempotent and never disposes borrowed geometry or source material',()=>{const f=fixture();let n=0;f.geometry.addEventListener('dispose',()=>n++);f.mat.addEventListener('dispose',()=>n++);const fx=attachSurfaceEffects(f.root,createSurfaceEngine(),[-1,2]);fx.dispose();fx.dispose();assert.equal(n,0);});
test('Materials with alpha cutouts fail closed to normal model display',()=>{const f=fixture(new THREE.MeshStandardMaterial({alphaTest:.5}));assert.equal(attachSurfaceEffects(f.root,createSurfaceEngine(),[-1,2]),null);assert.equal(f.mesh.material,f.mat);});
test('Morph/skinned geometry is not silently treated as a static effect profile',()=>{const f=fixture();f.mesh.isSkinnedMesh=true;assert.equal(attachSurfaceEffects(f.root,createSurfaceEngine(),[-1,2]),null);});
test('Masked material uniforms update without recompiling programs',()=>{const f=fixture(),e=createSurfaceEngine(),fx=attachSurfaceEffects(f.root,e,[-1,2]);const material=f.mesh.material,version=material.version;fx.update({...e.state,level:.4,mode:'reveal',scanning:true},1.4);assert.equal(fx.uniforms.uDthLevel.value,.4);assert.equal(fx.uniforms.uDthReveal.value,1);assert.equal(material.version,version);fx.dispose();});
