import test from 'node:test';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import sharp from 'sharp';
import { makeApp } from '../backend/commerce/app.mjs';
import { Product, Vehicle, User, Session, Order } from '../backend/commerce/models.mjs';
import { Conversation, Message } from '../backend/commerce/support/models.mjs';
const uri=process.env.TEST_MONGO_URI;
if(!uri || !/^mongodb:\/\/127\.0\.0\.1:\d+\/dth_[a-z_]+_test$/.test(uri))throw new Error('Use a dedicated local dth_*_test database. Never run cleanup tests on application data.');
const catalog=JSON.parse(await readFile(new URL('../shared/catalog.json',import.meta.url),'utf8'));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<60;i++){if(await fn())return;await sleep(80);}throw new Error('Timed out waiting for live event');}
await test('Real HTTP + MongoDB support and admin integration',async t=>{
  await mongoose.connect(uri);await mongoose.connection.dropDatabase();
  await Promise.all([Product,Vehicle,User,Session,Order,Conversation,Message].map(m=>m.init()));
  await Product.create(catalog.products);await Vehicle.create(catalog.vehicles);
  let app,server,base;const streams=[];
  async function start(){app=await makeApp();server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/api/shop`;}
  async function stop(){app.locals.supportHub.close();await new Promise(r=>server.close(r));}
  await start();
  const origin='http://127.0.0.1:5173',password='IsolatedSupportTest2026!';
  async function request(actor,path,body,method=body===undefined?'GET':'POST',extra={}){
    const response=await fetch(base+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(actor?{Cookie:actor.cookie,'X-CSRF-Token':actor.csrf}:{}),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});
    return {status:response.status,headers:response.headers,data:await response.json().catch(()=>({}))};
  }
  async function register(email){const r=await request(null,'/auth/register',{email,password,role:'admin'});assert.equal(r.status,201);return {cookie:r.headers.get('set-cookie').split(';')[0],csrf:r.data.csrf,id:r.data.user.id,email};}
  async function stream(actor){const ctrl=new AbortController(),events=[];const res=await fetch(base+'/chat/events',{headers:{Cookie:actor.cookie,Origin:origin},signal:ctrl.signal});assert.equal(res.status,200);const reader=res.body.getReader();let text='';const done=(async()=>{try{while(true){const {value,done}=await reader.read();if(done)break;text+=new TextDecoder().decode(value);let end;while((end=text.indexOf('\n\n'))>=0){const frame=text.slice(0,end);text=text.slice(end+2);const kind=/event: (.+)/.exec(frame)?.[1],raw=/data: (.+)/.exec(frame)?.[1];if(kind&&raw)events.push({kind,data:JSON.parse(raw)});}}}catch{}})();const handle={ctrl,events,done};streams.push(handle);await until(()=>events.some(e=>e.kind==='ready'));return handle;}
  try{
    const customer=await register('support-customer@example.test'),other=await register('support-other@example.test'),admin=await register('support-agent@example.test');
    await User.updateOne({_id:admin.id},{$set:{role:'admin'}});
    let conversation,message,imageMessage,customerStream,adminStream,otherStream;
    await t.test('Public registration cannot grant administrator privileges',async()=>assert.equal((await User.findById(customer.id)).role,'customer'));
    await t.test('Unauthenticated and customer admin requests are denied',async()=>{assert.equal((await request(null,'/admin/studio/overview')).status,401);assert.equal((await request(customer,'/admin/studio/products')).status,403);assert.equal((await request(customer,'/admin/studio/orders')).status,403);});
    await t.test('Customer opens exactly one conversation',async()=>{const a=await request(customer,'/chat/conversations',{}),b=await request(customer,'/chat/conversations',{});assert.equal(a.status,200);assert.equal(a.data.data.id,b.data.data.id);conversation=a.data.data.id;assert.equal(await Conversation.countDocuments({customerId:customer.id}),1);});
    await t.test('Conversation history and context enforce ownership',async()=>{assert.equal((await request(other,`/chat/conversations/${conversation}/messages`)).status,404);assert.equal((await request(customer,`/chat/conversations/${conversation}/context`)).status,403);assert.equal((await request(admin,`/chat/conversations/${conversation}/context`)).status,200);});
    await t.test('SSE uses authenticated streams and rejects foreign origins',async()=>{assert.equal((await request(null,'/chat/events')).status,401);assert.equal((await request(customer,'/chat/events',undefined,'GET',{Origin:'https://evil.invalid'})).status,403);customerStream=await stream(customer);adminStream=await stream(admin);otherStream=await stream(other);});
    const path=`/chat/conversations/${conversation}/messages`,clientId=randomUUID();
    await t.test('Text is stored before acknowledgement and realtime events target owner and staff only',async()=>{const before=adminStream.events.length;const r=await request(customer,path,{clientId,text:'Is this suspension suitable?',senderRole:'admin'});assert.equal(r.status,201);message=r.data.data;assert.equal(message.senderRole,'customer');assert.equal(await Message.countDocuments({id:message.id}),1);await until(()=>adminStream.events.slice(before).some(e=>e.kind==='change'&&e.data.conversationId===conversation));assert.equal(otherStream.events.some(e=>e.kind==='change'&&e.data.conversationId===conversation),false);});
    await t.test('A retry returns the same message; conflicting payload is rejected',async()=>{const r=await request(customer,path,{clientId,text:'Is this suspension suitable?'});assert.equal(r.data.data.id,message.id);assert.equal(await Message.countDocuments({conversationId:conversation}),1);assert.equal((await request(customer,path,{clientId,text:'different'})).status,409);});
    await t.test('Origin and CSRF are checked before accepting messages',async()=>{assert.equal((await request(customer,path,{clientId:randomUUID(),text:'bad'},'POST',{'X-CSRF-Token':'wrong'})).status,403);assert.equal((await request(customer,path,{clientId:randomUUID(),text:'bad'},'POST',{Origin:'https://evil.invalid'})).status,403);});
    await t.test('Malformed image is rejected and not persisted',async()=>{const n=await Message.countDocuments();assert.equal((await request(customer,path,{clientId:randomUUID(),image:{mime:'image/png',base64:Buffer.from('<script/>').toString('base64')}})).status,400);assert.equal(await Message.countDocuments(),n);});
    await t.test('Real image upload is re-encoded and protected from other customers',async()=>{const png=await sharp({create:{width:40,height:30,channels:3,background:'#00aacc'}}).png().toBuffer();const r=await request(customer,path,{clientId:randomUUID(),text:'Photo of the part',image:{mime:'image/png',base64:png.toString('base64')}});assert.equal(r.status,201);imageMessage=r.data.data;assert.equal(imageMessage.image.mime,'image/webp');assert.equal(imageMessage.image.data,undefined);const img=await fetch(base+imageMessage.image.path,{headers:{Cookie:admin.cookie}});assert.equal(img.status,200);assert.equal(img.headers.get('content-type'),'image/webp');assert.ok((await img.arrayBuffer()).byteLength>0);assert.equal((await request(other,imageMessage.image.path)).status,404);assert.equal((await request(null,imageMessage.image.path)).status,401);});
    await t.test('Typing events are ephemeral and scoped',async()=>{const n=await Message.countDocuments();await request(admin,`/chat/conversations/${conversation}/typing`,{active:true});await until(()=>customerStream.events.some(e=>e.kind==='typing'&&e.data.role==='admin'&&e.data.active));assert.equal(await Message.countDocuments(),n);});
    await t.test('Staff replies arrive in customer history',async()=>{const r=await request(admin,path,{clientId:randomUUID(),text:'Thank you. Please confirm your vehicle year.'});assert.equal(r.status,201);assert.equal(r.data.data.senderRole,'admin');const list=await request(customer,path);assert.ok(list.data.data.some(m=>m.id===r.data.data.id));});
    await t.test('Unread and read receipts use saved sequence positions',async()=>{const before=await request(admin,'/chat/conversations');assert.equal(before.data.data[0].unread,2);const list=await request(admin,path);const seq=list.data.conversation.lastMessageSeq;assert.equal((await request(admin,`/chat/conversations/${conversation}/read`,{seq})).status,200);assert.equal((await request(admin,'/chat/conversations')).data.data[0].unread,0);assert.equal((await request(customer,`/chat/conversations/${conversation}/read`,{seq:999999})).status,400);});
    await t.test('Only staff can resolve; a new message reopens the thread',async()=>{const statusPath=`/chat/conversations/${conversation}/status`;assert.equal((await request(customer,statusPath,{status:'resolved'},'PUT')).status,403);assert.equal((await request(admin,statusPath,{status:'resolved'},'PUT')).status,200);await request(customer,path,{clientId:randomUUID(),text:'One more question'});assert.equal((await Conversation.findOne({id:conversation})).status,'open');});
    await t.test('Concurrent retry creates one stored message',async()=>{const payload={clientId:randomUUID(),text:'Exactly one retry'};const responses=await Promise.all([request(customer,path,payload),request(customer,path,payload)]);assert.equal(responses[0].data.data.id,responses[1].data.data.id);assert.equal(await Message.countDocuments({clientId:payload.clientId}),1);});
    await t.test('History cursors allow replay without duplicates',async()=>{const r=await request(admin,`${path}?after=${message.seq}`);assert.ok(r.data.data.every(m=>m.seq>message.seq));const ids=r.data.data.map(m=>m.id);assert.equal(new Set(ids).size,ids.length);});
    await t.test('Product editor preserves metadata, rejects stale edits and hides products',async()=>{let current=(await request(admin,'/admin/studio/products/apex-suspension')).data.data;const data={...current,name:'Reviewed Apex Coilover',specs:{'Review detail':'Preserved'},active:false,expectedUpdatedAt:current.updatedAt};const saved=await request(admin,'/admin/studio/products/apex-suspension',data,'PUT');assert.equal(saved.status,200);assert.equal(saved.data.data.specs['Review detail'],'Preserved');assert.equal((await request(admin,'/admin/studio/products/apex-suspension',data,'PUT')).status,409);assert.equal((await request(null,'/products')).data.data.some(p=>p.id==='apex-suspension'),false);const restored={...saved.data.data,active:true,expectedUpdatedAt:saved.data.data.updatedAt};assert.equal((await request(admin,'/admin/studio/products/apex-suspension',restored,'PUT')).status,200);});
    await t.test('New product validation and duplicate protection',async()=>{const original=(await request(admin,'/admin/studio/products/apex-suspension')).data.data;const fresh={...original,id:'support-test-part',name:'Support test part'};assert.equal((await request(admin,'/admin/studio/products',fresh)).status,201);assert.equal((await request(admin,'/admin/studio/products',fresh)).status,409);assert.equal((await request(admin,'/admin/studio/products',{...fresh,id:'bad-price',price:-1})).status,400);});
    await t.test('Messages survive API restart and are loaded from MongoDB',async()=>{for(const s of streams)s.ctrl.abort();await Promise.all(streams.map(s=>s.done));await stop();await start();const r=await request(customer,path);assert.equal(r.status,200);assert.ok(r.data.data.some(m=>m.id===imageMessage.id));});
    await t.test('Logout invalidates image and stream access',async()=>{const s=await stream(customer);await request(customer,'/auth/logout',{});await until(()=>s.events.some(e=>e.kind==='session-ended'));assert.equal((await request(customer,imageMessage.image.path)).status,401);});
    await t.test('Account deletion removes customer support messages and images',async()=>{const r=await request(null,'/auth/login',{email:customer.email,password});customer.cookie=r.headers.get('set-cookie').split(';')[0];customer.csrf=r.data.csrf;assert.equal((await request(customer,'/auth/account',{password},'DELETE')).status,200);assert.equal(await Conversation.countDocuments({customerId:customer.id}),0);assert.equal(await Message.countDocuments({conversationId:conversation}),0);});
  }finally{for(const s of streams)s.ctrl.abort();await Promise.all(streams.map(s=>s.done));await stop();await mongoose.connection.dropDatabase();await mongoose.disconnect();}
});
