import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { CHAT_LIMITS, chatId, messageInput, pageNumber, sequence, searchText, literalPattern } from '../shared/support.mjs';
import { normalizeChatImage } from '../backend/commerce/support/images.mjs';
import { isChatMessageRequest } from '../backend/commerce/support/routes.mjs';
const input=extra=>({clientId:randomUUID(),text:' Hello ',...extra});
test('Message text is trimmed and sender fields are never trusted',()=>{const value=messageInput(input({senderRole:'admin',senderId:'fake'}));assert.equal(value.text,'Hello');assert.equal(value.senderRole,undefined);assert.equal(value.senderId,undefined);});
test('Empty messages are rejected',()=>assert.throws(()=>messageInput(input({text:'   '}))));
test('Long messages are rejected',()=>assert.throws(()=>messageInput(input({text:'x'.repeat(3001)}))));
test('Malformed body and client id are rejected',()=>{for(const v of [null,[],{},input({clientId:'../private'})])assert.throws(()=>messageInput(v));});
test('Image-only messages are allowed after transport validation',()=>assert.equal(messageInput(input({text:'',image:{mime:'image/png',base64:'aGVsbG8='}})).text,''));
test('SVG, HTML and animated upload formats are not allowed',()=>{for(const mime of ['image/svg+xml','text/html','image/gif'])assert.throws(()=>messageInput(input({image:{mime,base64:'aGVsbG8='}})));});
test('Malformed and oversized base64 are rejected',()=>{for(const base64 of ['','a','----',' '.repeat(8),'A'.repeat(Math.ceil(CHAT_LIMITS.uploadBytes/3)*4+4)])assert.throws(()=>messageInput(input({image:{mime:'image/png',base64}})));});
test('Cursor and pagination values are bounded',()=>{assert.equal(pageNumber('2'),2);assert.equal(sequence(0),0);for(const v of ['0','-1','1.5','100000',{}])assert.throws(()=>pageNumber(v));for(const v of [NaN,-1,Infinity,1.2])assert.throws(()=>sequence(v));});
test('Conversation IDs cannot contain paths',()=>{assert.equal(chatId(randomUUID()).length,36);assert.throws(()=>chatId('../orders'));});
test('Search text is literal, not an arbitrary regular expression',()=>{assert.equal(new RegExp(literalPattern('a.*[x]')).test('a.*[x]'),true);assert.equal(new RegExp(literalPattern('a.*[x]')).test('anythingx'),false);assert.throws(()=>searchText('x'.repeat(101)));});
test('Large parser exception matches only authenticated image-message POST',()=>{const id=randomUUID();assert.equal(isChatMessageRequest({method:'POST',path:`/api/shop/chat/conversations/${id}/messages`}),true);for(const path of ['/api/shop/auth/register','/api/shop/admin/products',`/api/shop/chat/conversations/${id}/read`])assert.equal(isChatMessageRequest({method:'POST',path}),false);});
test('Actual PNG is re-encoded to bounded WebP and metadata is stripped',async()=>{const input=await sharp({create:{width:2000,height:1000,channels:3,background:'#00aadd'}}).png().toBuffer();const result=await normalizeChatImage({mime:'image/png',base64:input.toString('base64')});const meta=await sharp(result.data).metadata();assert.equal(meta.format,'webp');assert.equal(meta.width,1600);assert.equal(meta.height,800);assert.equal(meta.exif,undefined);assert.ok(result.bytes<CHAT_LIMITS.storedBytes);});
test('An extension or declared MIME is not enough to validate an image',async()=>{await assert.rejects(normalizeChatImage({mime:'image/png',base64:Buffer.from('<svg><script>alert(1)</script></svg>').toString('base64')}));const b=await sharp({create:{width:10,height:10,channels:3,background:'white'}}).jpeg().toBuffer();await assert.rejects(normalizeChatImage({mime:'image/png',base64:b.toString('base64')}));});
test('Truncated raster input is rejected without leaking decoder details',async()=>{await assert.rejects(normalizeChatImage({mime:'image/png',base64:Buffer.from([137,80,78,71,13,10,26,10]).toString('base64')}),/safely decoded/);});
