import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { studioRequest } from '../api';
import { useStore } from '../useStore';
import { useSupport } from '../support/SupportProvider';
import ChatThread from '../support/ChatThread';
import useAdminData from './useAdminData';
import { formatMoney } from '../../../../shared/domain.mjs';
function CustomerContext({id}){const {data,error,reload}=useAdminData(`/chat/conversations/${id}/context`),info=data?.data;return <aside className="dth-inbox-context"><span className="dth-admin-kicker">CUSTOMER CONTEXT</span>{error?<p role="alert">{error}<button onClick={reload}>Retry</button></p>:!info?<p>Loading customer…</p>:<><div className="dth-inbox-avatar">{info.customer.email.slice(0,1).toUpperCase()}</div><h3>{info.customer.email}</h3><small>Saved vehicle</small><p>{info.vehicle?`${info.vehicle.make} ${info.vehicle.model} · ${info.vehicle.year}`:'No saved vehicle'}</p><h4>Recent demo orders</h4>{!info.orders.length?<p>No orders yet.</p>:info.orders.map(o=><Link key={o.id} className="dth-inbox-order" to={`/admin/orders/${o.id}`}><strong>{o.id}</strong><span>{formatMoney(o.total)} ↗</span></Link>)}</>}</aside>;}
export default function Inbox(){
  const [params,setParams]=useSearchParams(),support=useSupport(),store=useStore(),[draft,setDraft]=useState(params.get('q')||''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[meta,setMeta]=useState(null);
  const id=params.get('thread')||'',page=Number(params.get('page'))||1,status=params.get('status')||'',q=params.get('q')||'';
  const query=new URLSearchParams({page:String(page),...(status?{status}:{}),...(q?{q}:{})});
  const result=useAdminData(`/chat/conversations?${query}`,support.revision),rows=result.data?.data||[];
  const chosen=(meta?.id===id?meta:rows.find(c=>c.id===id));
  function change(values){const next=new URLSearchParams(params);Object.entries(values).forEach(([k,v])=>v?next.set(k,v):next.delete(k));setParams(next);}
  async function resolve(){if(busy)return;setBusy(true);setError('');try{await studioRequest(`/chat/conversations/${id}/status`,{method:'PUT',body:JSON.stringify({status:chosen?.status==='resolved'?'open':'resolved'})});support.refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div className="dth-admin-enter"><header className="dth-admin-heading"><div><span>CUSTOMER CARE / REALTIME</span><h1>Inbox</h1></div><span className="dth-admin-live" data-live={support.status==='live'}>{support.status==='live'?'● Connected':'○ Reconnecting'}</span></header><div className="dth-inbox" data-selected={!!id}><aside className="dth-inbox-list"><form onSubmit={e=>{e.preventDefault();change({q:draft,page:''});}}><label className="dth-chat-sr" htmlFor="support-search">Search conversations by email</label><input id="support-search" placeholder="Search customer email" value={draft} maxLength={100} onChange={e=>setDraft(e.target.value)}/><button aria-label="Search conversations">⌕</button></form><div className="dth-inbox-filters">{[['','All'],['open','Open'],['resolved','Resolved']].map(([value,label])=><button key={value} aria-pressed={status===value} onClick={()=>change({status:value,page:''})}>{label}</button>)}</div>{result.error?<p className="dth-admin-error" role="alert">{result.error}<button onClick={result.reload}>Retry</button></p>:!result.data?<p className="dth-admin-loading">Loading conversations…</p>:!rows.length?<p className="dth-chat-empty">No conversations yet. Customers can start one using Support in the store.</p>:rows.map(c=><button key={c.id} className="dth-inbox-row" aria-current={id===c.id?'true':undefined} onClick={()=>change({thread:c.id})}><span className="dth-inbox-avatar">{c.customer.email.slice(0,1).toUpperCase()}</span><span><strong>{c.customer.email}</strong><small>{c.lastPreview||'New conversation'}</small><em>{c.status==='resolved'?'Resolved':'Open'}</em></span>{c.unread>0&&<b>{c.unread>99?'99+':c.unread}</b>}</button>)}{result.data?.total>30&&<div className="dth-admin-pagination"><button disabled={page===1} onClick={()=>change({page:String(page-1)})}>Previous</button><span>{page}</span><button disabled={page*30>=result.data.total} onClick={()=>change({page:String(page+1)})}>Next</button></div>}</aside><section className="dth-inbox-thread">{!id?<div className="dth-inbox-empty"><span>↗</span><h2>A better conversation starts here.</h2><p>Choose a customer to reply. Photos and messages stay in their conversation.</p></div>:<><header className="dth-inbox-thread-heading"><button className="dth-inbox-back" aria-label="Back to conversations" onClick={()=>change({thread:''})}>←</button><div><strong>{chosen?.customer?.email||'Conversation'}</strong><small>{chosen?.status==='resolved'?'Resolved · new messages reopen this conversation':'Customer support'}</small></div><button disabled={busy||!chosen} onClick={resolve}>{busy?'Saving…':chosen?.status==='resolved'?'Reopen':'Resolve'}</button></header>{error&&<p className="dth-admin-error" role="alert">{error}</p>}<ChatThread key={`${store.user.id}:${id}`} conversationId={id} onMeta={setMeta}/></>}</section>{id&&<CustomerContext key={id} id={id}/>}</div></div>;
}
