"""Compiled React in explicit FLOW mode. No API process and no MongoDB process."""
import json,re,os,uuid
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
base=os.environ.get('DTH_FLOW_URL','http://127.0.0.1:4173')
out=Path('test-results/account-flow');out.mkdir(parents=True,exist_ok=True)
checks,errors,api_requests=[],[],[]
def ok(name):checks.append(name);print('PASS:',name,flush=True)
def capture(page,name):page.screenshot(path=str(out/(name+'.png')),full_page=True)
def no_overflow(page):assert page.evaluate('document.documentElement.scrollWidth <= innerWidth + 1'),'Horizontal overflow'
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--use-angle=swiftshader','--enable-unsafe-swiftshader'])
    context=browser.new_context(viewport={'width':1440,'height':1000})
    page=context.new_page();page.set_default_timeout(18000)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:api_requests.append(r.url) if '/api/shop/' in r.url else None)
    try:
        page.goto(base+'/account');expect(page.get_by_role('heading',name='Welcome back.')).to_be_visible()
        expect(page.locator('.dth-demo-banner')).to_contain_text('FLOW DEMO / NO DATABASE')
        expect(page.get_by_role('note')).to_contain_text('not real authentication')
        expect(page.locator('[data-account-scene=ready]')).to_be_visible();ok('Account 3D rendered in flow mode with no backend')
        page.get_by_role('button',name='Explode 3D bearing').click()
        expect(page.locator('[data-account-scene]')).to_have_attribute('data-assembly','expanded')
        page.wait_for_timeout(600);capture(page,'01-exploded-bearing')
        page.get_by_role('button',name='Assemble 3D bearing').click()
        page.get_by_role('button',name='Pause studio animation').click();expect(page.locator('[data-account-scene]')).to_have_attribute('data-motion','off')
        page.get_by_role('button',name='Play studio animation').click();ok('Explode / assemble / pause / play controls work')
        page.get_by_label('Email',exact=True).focus();expect(page.locator('[data-account-scene]')).to_have_attribute('data-phase','identify')
        page.get_by_label('Password',exact=True).focus();expect(page.locator('[data-account-scene]')).to_have_attribute('data-phase','password');ok('3D assembly responds to form focus without reading field contents')
        page.get_by_label('Email',exact=True).fill('demo@dth.test');page.get_by_label('Password',exact=True).fill('wrong password here')
        page.get_by_role('button',name='Sign in',exact=True).click();expect(page.get_by_role('alert')).to_contain_text('incorrect');ok('Incorrect rehearsal credential displays error')
        page.get_by_role('button',name='Create account',exact=True).click()
        page.get_by_label('Email',exact=True).fill('flow-'+uuid.uuid4().hex[:8]+'@dth.test')
        page.get_by_label('Password',exact=True).fill('DthFlow2026!');page.get_by_label('Confirm password',exact=True).fill('wrong confirmation')
        page.get_by_role('button',name='Create account',exact=True).click();expect(page.get_by_role('alert')).to_contain_text('do not match')
        page.get_by_label('Confirm password',exact=True).fill('DthFlow2026!');page.get_by_role('button',name='Create account',exact=True).click()
        expect(page.get_by_role('heading',name='Your account.')).to_be_visible();ok('Fixture registration and password confirmation flow')
        page.get_by_role('navigation',name='Account navigation').get_by_role('link',name='Saved vehicle').click()
        page.get_by_label('Make',exact=True).select_option(label='Demo Moto');page.get_by_label('Model',exact=True).select_option(label='Street 155');page.get_by_label('Year',exact=True).select_option(label='2022')
        page.get_by_role('button',name='Save vehicle',exact=True).click();expect(page.locator('main p[role=status]')).to_contain_text('Demo vehicle saved in this tab.')
        page.reload();expect(page.get_by_label('Year',exact=True)).to_have_value('2022');ok('Vehicle is saved and restored from this demo tab')
        page.goto(base+'/shop');page.get_by_role('heading',name='Apex Coilover',exact=True).get_by_role('link').click()
        page.get_by_role('link',name='Open product & 3D').click();page.wait_for_url(base+'/products/apex-suspension')
        page.get_by_role('button',name='Add to bag',exact=True).click();page.goto(base+'/bag')
        page.get_by_role('button',name='Review order',exact=True).click()
        expect(page.get_by_role('button',name='Place simulated order',exact=True)).to_be_disabled()
        page.get_by_role('checkbox').check();page.get_by_role('button',name='Place simulated order',exact=True).click()
        page.wait_for_url(re.compile(re.escape(base)+r'/order-complete\?order=FLOW-'))
        expect(page.get_by_role('heading',name='Your demo order is confirmed.')).to_be_visible()
        expect(page.get_by_text('Demo data in this tab only — not MongoDB',exact=True)).to_be_visible()
        capture(page,'02-flow-receipt');ok('Shop -> Quick View -> Product -> Bag -> Review -> fixture order')
        page.reload();expect(page.get_by_role('heading',name='Your demo order is confirmed.')).to_be_visible();ok('Receipt survives F5 in tab, explicitly not DB persistence')
        page.goto(base+'/account?view=orders');page.get_by_role('button',name=re.compile(r'FLOW-')).first.click()
        expect(page.get_by_role('heading',name='Order detail.')).to_be_visible();expect(page.get_by_text('Apex Coilover',exact=True)).to_be_visible()
        page.reload();expect(page.get_by_text('Apex Coilover',exact=True)).to_be_visible();ok('Account history reopens same fixture order after F5')
        page.goto(base+'/account?view=orders');page.get_by_label('Search orders',exact=True).fill('no matching fixture');page.get_by_role('button',name='Search',exact=True).click()
        expect(page.get_by_role('heading',name='No matching orders.')).to_be_visible();page.get_by_role('button',name='Reset search').click()
        expect(page.get_by_role('button',name=re.compile(r'FLOW-')).first).to_be_visible();ok('Search empty state and reset')
        page.goto(base+'/account');capture(page,'03-member-overview')
        for width in [320,390,768,1440]:
            page.set_viewport_size({'width':width,'height':900})
            for view in ['', '?view=vehicle','?view=orders','?view=security']:
                page.goto(base+'/account'+view);expect(page.locator('main h1')).to_be_visible();page.wait_for_timeout(450);no_overflow(page)
            capture(page,'04-account-'+str(width))
        ok('All account views fit 320 / 390 / 768 / 1440px')
        page.emulate_media(reduced_motion='reduce');page.goto(base+'/account');expect(page.locator('[data-account-scene]')).to_have_attribute('data-motion','off')
        assert page.locator('[data-motion-panel]').count()==0 or page.locator('[data-motion-panel]').evaluate('e=>e.getAnimations().every(a=>a.playState!=="running")')
        ok('Reduced motion stops continuous 3D and route transition')
        page.goto(base+'/account?view=security');page.get_by_role('button',name='Delete account',exact=True).click()
        dialog=page.get_by_role('dialog');expect(dialog.get_by_role('button',name='Cancel',exact=True)).to_be_focused();page.keyboard.press('Escape');expect(dialog).not_to_be_visible();ok('Destructive action cancellation and focus')
        page.get_by_role('button',name='Sign out',exact=True).click();expect(page.get_by_role('heading',name='Welcome back.')).to_be_visible()
        page.goto(base+'/account?return=/bag');page.get_by_label('Email',exact=True).fill('demo@dth.test');page.get_by_label('Password',exact=True).fill('DthFlow2026!');page.get_by_role('button',name='Sign in',exact=True).click()
        page.wait_for_url(base+'/bag');ok('Login returns to exact bag URL')
        assert page.evaluate('localStorage.getItem("dth.commerce.bag.v1")') is None
        assert 'DthFlow2026!' not in page.evaluate('sessionStorage.getItem("dth.flow.rehearsal.v1")')
        ok('Flow storage is separate from API storage and stores no password')
        assert not api_requests,api_requests;ok('ZERO API requests across the complete rehearsal')
        assert not errors,errors;ok('No uncaught browser exceptions')
        fallback=browser.new_context(viewport={'width':1440,'height':950})
        fallback.add_init_script("const orig=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return t.startsWith('webgl')?null:orig.call(this,t,...a)}")
        fp=fallback.new_page();fp.goto(base+'/account');expect(fp.get_by_role('heading',name='Welcome back.')).to_be_visible()
        expect(fp.locator('[data-account-scene=fallback]')).to_be_visible();expect(fp.get_by_role('button',name='Sign in',exact=True)).to_be_enabled()
        ok('WebGL unavailable: SVG remains and account form stays usable');fallback.close()
    except Exception:
        capture(page,'failure');(out/'failure.html').write_text(page.content(),encoding='utf8');raise
    finally:
        (out/'results.json').write_text(json.dumps({'checks':checks,'browserErrors':errors,'apiRequests':api_requests},indent=2));browser.close()
